import type { SeGrowthPlanData } from "./types";

export const DEMO_GROWTH_PLAN: SeGrowthPlanData = {
  hasPlan: true,
  signals: [
    { icon: "📉", label: "Sim trend", value: "78→55 (↓23 pts)", color: "#B83128", detail: "Declining across 5 sessions" },
    { icon: "🚧", label: "Gate status", value: "Blocked 13 days", color: "#B83128", detail: "Gate 1 sign-off pending" },
    { icon: "🎯", label: "Discovery score", value: "45/100", color: "#D4810A", detail: "Lowest on team" },
    { icon: "🏆", label: "Certifications", value: "0 of 8", color: "#D4810A", detail: "None started yet" },
    { icon: "📋", label: "Ramp progress", value: "12%", color: "#B83128", detail: "Behind expected pace" },
    { icon: "🗓️", label: "Coaching sessions", value: "0", color: "#B83128", detail: "No 1:1s recorded yet" },
  ],
  goals: [
    {
      icon: "🛠️",
      title: "Gate 1 Recovery Plan",
      quarter: "Q2 2026",
      source: "Manager · Urgent",
      progress: 5,
      tag: "AT RISK",
      tagBg: "rgba(184,49,40,.08)",
      tagColor: "#B83128",
      progressColor: "#B83128",
      dueDate: "Jul 31",
      dueDateColor: "#B83128",
      bg: "#FFF8F7",
      borderColor: "rgba(184,49,40,.2)",
      milestones: [
        { label: "Daily 30-min sim practice ×5", date: "Jul 18", done: false },
        { label: "Weekly 1:1 coaching session", date: "Jul 21", done: false },
        { label: "Gate 1 sign-off meeting", date: "Jul 31", done: false },
      ],
    },
    {
      icon: "🎯",
      title: "Discovery Fundamentals: Enterprise Depth",
      quarter: "Q3 2026",
      source: "AI · Score 45",
      progress: 0,
      tag: "NOT STARTED",
      tagBg: "#F5F4F0",
      tagColor: "#A09D98",
      progressColor: "#A09D98",
      dueDate: "Sep 15",
      dueDateColor: "#6B6860",
      bg: "#FAFAF8",
      borderColor: "#EEECE8",
      milestones: [
        { label: "Multi-stakeholder sim ×3", date: "Aug 10", done: false },
        { label: "Healthcare discovery scenario", date: "Aug 25", done: false },
        { label: "Score ≥72 on rubric", date: "Sep 10", done: false },
      ],
    },
    {
      icon: "🏆",
      title: "Core SE Certification: IIQ + Identity Security",
      quarter: "Q3 2026",
      source: "AI · 0 of 8 certs",
      progress: 0,
      tag: "NOT STARTED",
      tagBg: "#F5F4F0",
      tagColor: "#A09D98",
      progressColor: "#A09D98",
      dueDate: "Sep 30",
      dueDateColor: "#6B6860",
      bg: "#FAFAF8",
      borderColor: "#EEECE8",
      milestones: [
        { label: "Identity Security Fundamentals cert", date: "Aug 15", done: false },
        { label: "SailPoint IIQ Core cert", date: "Sep 5", done: false },
        { label: "Manager sign-off", date: "Sep 30", done: false },
      ],
    },
  ],
  quarters: [
    { label: "Q1", summary: "Plan not started", needsAction: false, bg: "#fff", border: "#F0EFEB", labelColor: "#A09D98" },
    {
      label: "Q2",
      summary: "Gate 1 recovery — 5%",
      needsAction: true,
      bg: "#FFFAF5",
      border: "rgba(212,129,10,.2)",
      labelColor: "#D4810A",
    },
    {
      label: "Q3",
      summary: "Discovery + 2 certs",
      needsAction: false,
      bg: "#F0F7FF",
      border: "rgba(0,113,206,.15)",
      labelColor: "#0071CE",
    },
    { label: "Q4", summary: "Readiness review", needsAction: false, bg: "#fff", border: "#F0EFEB", labelColor: "#A09D98" },
  ],
};

export const DEMO_GROWTH_PLAN_EMPTY: SeGrowthPlanData = {
  hasPlan: false,
  signals: [],
  goals: [],
  quarters: [],
};
