import type { SeGrowthPlanData } from "./types";

export const DEMO_GROWTH_PLAN: SeGrowthPlanData = {
  hasPlan: true,
  signals: [
    { icon: "signal", label: "Sim trend", value: "78 to 55, down 23", color: "#B42318", detail: "Declining across 5 sessions" },
    { icon: "signal", label: "Gate status", value: "Blocked 13 days", color: "#B42318", detail: "Gate 1 sign-off pending" },
    { icon: "signal", label: "Discovery score", value: "45 of 100", color: "#8A5300", detail: "Lowest on team" },
    { icon: "signal", label: "Certifications", value: "0 of 8", color: "#8A5300", detail: "None started yet" },
    { icon: "signal", label: "Ramp progress", value: "12%", color: "#B42318", detail: "Behind expected pace" },
    { icon: "signal", label: "Coaching sessions", value: "0", color: "#B42318", detail: "No 1:1s recorded yet" },
  ],
  goals: [
    {
      icon: "signal",
      title: "Gate 1 Recovery Plan",
      quarter: "Q2 2026",
      source: "From your manager, urgent",
      progress: 5,
      tag: "AT RISK",
      tagBg: "#FCEBEA",
      tagColor: "#B42318",
      progressColor: "#B42318",
      dueDate: "Jul 31",
      dueDateColor: "#B42318",
      bg: "#FCEBEA",
      borderColor: "#B42318",
      milestones: [
        { label: "Daily 30-min sim practice ×5", date: "Jul 18", done: false },
        { label: "Weekly 1:1 coaching session", date: "Jul 21", done: false },
        { label: "Gate 1 sign-off meeting", date: "Jul 31", done: false },
      ],
    },
    {
      icon: "signal",
      title: "Discovery Fundamentals: Enterprise Depth",
      quarter: "Q3 2026",
      source: "Suggested by AI, score 45",
      progress: 0,
      tag: "NOT STARTED",
      tagBg: "#E9EDF5",
      tagColor: "#4A5878",
      progressColor: "#B7C0D3",
      dueDate: "Sep 15",
      dueDateColor: "#4A5878",
      bg: "#FFFFFF",
      borderColor: "#D6DCE8",
      milestones: [
        { label: "Multi-stakeholder sim ×3", date: "Aug 10", done: false },
        { label: "Healthcare discovery scenario", date: "Aug 25", done: false },
        { label: "Score ≥72 on rubric", date: "Sep 10", done: false },
      ],
    },
    {
      icon: "signal",
      title: "Core SE Certification: IIQ + Identity Security",
      quarter: "Q3 2026",
      source: "Suggested by AI, 0 of 8 certifications",
      progress: 0,
      tag: "NOT STARTED",
      tagBg: "#E9EDF5",
      tagColor: "#4A5878",
      progressColor: "#B7C0D3",
      dueDate: "Sep 30",
      dueDateColor: "#4A5878",
      bg: "#FFFFFF",
      borderColor: "#D6DCE8",
      milestones: [
        { label: "Identity Security Fundamentals cert", date: "Aug 15", done: false },
        { label: "SailPoint IIQ Core cert", date: "Sep 5", done: false },
        { label: "Manager sign-off", date: "Sep 30", done: false },
      ],
    },
  ],
  quarters: [
    { label: "Q1", summary: "Plan not started", needsAction: false, bg: "#FFFFFF", border: "#D6DCE8", labelColor: "#4A5878" },
    {
      label: "Q2",
      summary: "Gate 1 recovery, 5% done",
      needsAction: true,
      bg: "#FBF1DF",
      border: "#8A5300",
      labelColor: "#8A5300",
    },
    {
      label: "Q3",
      summary: "Discovery + 2 certs",
      needsAction: false,
      bg: "#E5ECFA",
      border: "#3A62C0",
      labelColor: "#0033A1",
    },
    { label: "Q4", summary: "Readiness review", needsAction: false, bg: "#FFFFFF", border: "#D6DCE8", labelColor: "#4A5878" },
  ],
};

export const DEMO_GROWTH_PLAN_EMPTY: SeGrowthPlanData = {
  hasPlan: false,
  signals: [],
  goals: [],
  quarters: [],
};
