import type { HelpArticle } from "@/lib/help/types";

/** Help Center articles for the Manager portal. Labels match the UI in components/manager and components/programs. */
export const MANAGER_ARTICLES: HelpArticle[] = [
  {
    id: "mgr-today",
    title: "Your Today page",
    summary: "What the Today page shows, how your team is ordered most urgent first, and where to go next.",
    audience: ["manager"],
    category: "Getting started",
    keywords: ["home", "dashboard", "today", "most urgent first", "at risk", "avg readiness", "reviews waiting", "since friday"],
    overview: [
      "Today is the first page in the Manager portal. The strip at the top shows three numbers: \"Reviews waiting\" (with a note such as \"2 older than 3 days\" when items pass the 3-day review target), \"At risk\" and \"Avg readiness\". Between Avg readiness and Open inbox, a \"Since Friday\" message summarises recent practice, ramp activity, and who has gone quiet.",
      "The team list is titled \"Your team, most urgent first\". People are ordered by status: at risk first (lowest readiness first), then people with work waiting on you, then people who are on track. Among on-track people, anyone with a suggested action comes first.",
      "Someone is at risk when their readiness is under 60, or their coaching health is at risk or stalled. Readiness target is 70. Each row gives a short reason (for example \"No ramp plan assigned\" or \"2 steps overdue\") and one suggested action such as \"Assign a plan\", \"Assign practice\" or \"Schedule a 1:1\". Rows with nothing to do show \"Nothing needed\".",
      "The side rail shows how many people you coached in the last seven days, with a \"Book the rest\" or \"See your cadence\" link.",
    ],
    steps: [
      { title: "Check the numbers", body: "Read \"Reviews waiting\", \"At risk\" and \"Avg readiness\" at the top of the page. A red At risk number means at least one person needs attention." },
      { title: "Clear reviews first", body: "Click \"Open inbox\" to work through items waiting on you, oldest first." },
      { title: "Work the team list from the top", body: "Start with the first row. The reason column tells you why the person is listed and the action tells you what to do next." },
      { title: "Open a person", body: "Click a name to open that SE's detail workbench with their Overview and Coach columns." },
      { title: "Keep your coaching rhythm", body: "In the side rail, click \"Book the rest\" to go to Coaching cadence and see who you haven't coached in the last seven days." },
    ],
    links: [
      { label: "Open Today", href: "/manager" },
      { label: "Open Inbox", href: "/manager/inbox" },
    ],
    related: ["mgr-inbox", "mgr-se-workbench", "mgr-coaching-cadence", "mgr-roster"],
  },
  {
    id: "mgr-inbox",
    title: "Using the Inbox",
    summary: "Find every item waiting on your review, filter it, and open it in the review workbench.",
    audience: ["manager"],
    category: "Reviews",
    keywords: ["inbox", "queue", "review queue", "pending reviews", "sla", "older than 3 days", "filter", "waiting"],
    overview: [
      "The Inbox lists \"Items waiting on you, oldest first\". Item types are Sim cards, Challenges, Plan steps, Gates (certification gates), Deal preps, Pitches and Mentor notes. A type filter only appears when there is at least one item of that type.",
      "The header shows \"Waiting\" and \"Older than 3 days\". Three days is the review target; the Older than 3 days count turns red when anything has passed it.",
      "Nothing is sent to the SE until you click Approve or Request changes in the review workbench.",
    ],
    steps: [
      { title: "Open the Inbox", body: "Click Inbox in the left navigation. Items are listed oldest first with columns for Age, Type, Item, SE and Score." },
      { title: "Filter by type", body: "Click a type chip such as \"Sim cards\" or \"Plan steps\" to narrow the list. Each chip shows its count." },
      { title: "Filter by person or age", body: "Use the SE filter (\"Every SE\" or one name) and the age filter (\"Any age\", \"Older than 3 days\" or \"Today\")." },
      { title: "Open an item", body: "Click a row to open the review workbench. \"The work\" is on the left and \"Your sign-off\" is on the right." },
      { title: "Finish and move on", body: "Approve or request changes. The item leaves the list. When everything is done you see \"Inbox clear. Nice work.\"" },
    ],
    links: [{ label: "Open Inbox", href: "/manager/inbox" }],
    related: ["mgr-review-workbench", "mgr-bulk-approve", "mgr-review-history"],
  },
  {
    id: "mgr-review-workbench",
    title: "Reviewing work: sign-off, grade, Approve and Request changes",
    summary: "How to complete the coaching sign-off in the review workbench and what Approve does for each item type.",
    audience: ["manager"],
    category: "Reviews",
    keywords: ["review", "approve", "request changes", "sign-off", "coaching sign-off", "grade", "strength observed", "gap to address", "concrete next action", "readiness confidence", "live coaching attestation", "tier", "light", "required", "coaching brief"],
    overview: [
      "Every item except mentor notes uses a structured \"Coaching sign-off\". Its tier is shown as a tag and decides which fields you must fill in.",
      "Light (challenges, deal preps, pitches): \"Strength observed\" and \"Concrete next action\". Required (sim cards and ordinary plan steps): adds \"Gap to address\". Certification gates and plan steps that are segment gates use the strictest tier: when approving you also choose \"Readiness confidence, 1 to 5\" and can tick \"Live coaching attestation\" and describe \"What you observed\".",
      "Sim cards, challenges and pitches also take a \"Grade, 1 to 5\". Mentor notes use a single \"Feedback\" box instead of the sign-off fields.",
      "The \"Coaching brief\" panel above the fields is an AI draft that pre-fills your sign-off and suggests what to ask in your 1:1. Edit it before you send.",
      "Approve does something different per type, and the drawer tells you what. For example, approving a sim card validates the SE's simulation step, approving a gate plan step unlocks their next segment, and approving a certification gate clears it.",
    ],
    steps: [
      { title: "Open the item", body: "Click a row in the Inbox. Read \"The work\" on the left, including any \"SE notes\" or \"SE reflection\". For pitches, click \"Watch video pitch\"." },
      { title: "Review the AI draft", body: "Read the \"Coaching brief\" under \"Your sign-off\". It fills in the fields for you; rewrite anything that isn't what you saw." },
      { title: "Complete the sign-off fields", body: "Fill in \"Strength observed\", \"Gap to address\" (when shown) and \"Concrete next action\". Be specific; very short answers fail validation." },
      { title: "Set grade and confidence", body: "Where shown, enter \"Grade, 1 to 5\". For gates, select a \"Readiness confidence, 1 to 5\" rating before approving." },
      { title: "Approve or request changes", body: "Click \"Approve\" to sign off, or \"Request changes\" to send it back with your guidance. If a required field is missing you see \"Complete the coaching sign-off fields before approving.\"", tip: "Esc closes the drawer without sending anything." },
    ],
    links: [{ label: "Open Inbox", href: "/manager/inbox" }],
    related: ["mgr-inbox", "mgr-bulk-approve", "mgr-certifications", "mgr-mentees"],
  },
  {
    id: "mgr-bulk-approve",
    title: "Bulk approve strong sim cards",
    summary: "Approve several sim cards scoring 75 or higher at once from the Inbox.",
    audience: ["manager"],
    category: "Reviews",
    keywords: ["bulk", "approve all", "select", "sim card", "75", "batch approve"],
    overview: [
      "Only sim cards scoring 75 or higher can be approved in bulk. Every other item needs a full review in the workbench.",
      "Bulk approve reuses each card's own coaching points as the sign-off and sets the grade from the score. The server still validates each sign-off; cards that fail stay in the list and you are told to open each one.",
    ],
    steps: [
      { title: "Filter to sim cards", body: "In the Inbox, click the \"Sim cards\" chip so you only see sim cards." },
      { title: "Select cards", body: "Tick the checkbox on each eligible row, or tick the header checkbox to \"Select every sim card scoring 75 or higher\"." },
      { title: "Approve them", body: "Click \"Approve N\" in the selection bar. The approved cards leave the list." },
      { title: "Handle the rest", body: "If you see \"Those cards need a full review\", open each remaining card and complete the sign-off by hand." },
    ],
    links: [{ label: "Open Inbox", href: "/manager/inbox" }],
    related: ["mgr-inbox", "mgr-review-workbench"],
  },
  {
    id: "mgr-se-workbench",
    title: "Opening an SE's detail workbench",
    summary: "See one SE's ramp, gates and activity, schedule a 1:1, keep private notes, assign a simulation or change their mentor.",
    audience: ["manager"],
    category: "Team",
    keywords: ["se detail", "profile", "drawer", "schedule 1:1", "one on one", "talking points", "private coaching notes", "assign simulation", "reassign mentor", "ics"],
    overview: [
      "Click a person's name on Today, Roster or other team pages to open their workbench. It has two columns: \"Overview\" and \"Coach\".",
      "Overview covers their ramp plan, certification gates, development goals, simulation trend, recent activity and anything \"Sent back for changes\". Coach holds \"Mentor and notes\", \"Assign a simulation\", \"Field activity\" and \"Recent activity\".",
      "\"Private coaching notes\" are only visible to you.",
    ],
    steps: [
      { title: "Open the person", body: "Click their name in any team list. The workbench opens as a drawer." },
      { title: "Schedule a 1:1", body: "Click \"Schedule 1:1\". A calendar invite (.ics) downloads with up to four talking points; open it to add it to your calendar." },
      { title: "Copy talking points", body: "Click \"Copy talking points\" to put the full list on your clipboard for your 1:1 doc." },
      { title: "Keep private notes", body: "Under \"Private coaching notes\", type observations and commitments, then click \"Save notes\"." },
      { title: "Assign a simulation", body: "Under \"Assign a simulation\", search and pick a prompt template, set the details, and assign it. The SE starts it from Simulations." },
      { title: "Change their mentor", body: "Under \"Assigned mentor\", choose a mentor (or \"No mentor assigned\") and click \"Save mentor\". This only appears when the SE has a ramp plan." },
    ],
    links: [{ label: "Open Roster", href: "/manager/team" }],
    related: ["mgr-roster", "mgr-today", "mgr-readiness", "mgr-coaching-cadence"],
  },
  {
    id: "mgr-roster",
    title: "Team roster",
    summary: "See everyone who reports to you, grouped by status or as a sortable table.",
    audience: ["manager"],
    category: "Team",
    keywords: ["roster", "team", "direct reports", "status", "career gates", "at risk", "waiting on you", "on track"],
    overview: [
      "Team > Roster shows \"Your team.\" in two views: \"By status\" groups people into \"At risk\", \"Waiting on you\" and \"On track\"; \"Table\" lists everyone and lets you sort by clicking a column header.",
      "Career gates show as stamps per person (earned, ready, partly done, or not started).",
    ],
    steps: [
      { title: "Open the roster", body: "Click Team, then Roster." },
      { title: "Pick a view", body: "Use the \"Roster view\" switch to choose \"By status\" or \"Table\"." },
      { title: "Sort the table", body: "In Table view, click a column header to sort by it." },
      { title: "Open someone", body: "Click a person to open their detail workbench." },
    ],
    links: [{ label: "Open Roster", href: "/manager/team" }],
    related: ["mgr-se-workbench", "mgr-readiness", "mgr-today"],
  },
  {
    id: "mgr-readiness",
    title: "Team readiness and assigning practice",
    summary: "See where the team is thin by competency and send a simulation to the people below the bar.",
    audience: ["manager"],
    category: "Team",
    keywords: ["readiness", "competency", "distribution", "assign practice", "thin", "target 70", "below 60", "nudge"],
    overview: [
      "Team > Readiness shows team readiness by competency, worst first. Target is 70. Each competency splits people into below 60, close (60 to 69) and at target (70 or above).",
      "Switch between the \"Distribution\" and \"Table\" views. Competencies where someone is below 60 offer \"Assign practice to N\".",
    ],
    steps: [
      { title: "Open Readiness", body: "Click Team, then Readiness." },
      { title: "Find the weakest competency", body: "Competencies are listed worst first, so start at the top." },
      { title: "Assign practice", body: "Click \"Assign practice to N\". A drawer explains which SEs score below 60 on that competency." },
      { title: "Pick a simulation", body: "Choose a prompt template in the drawer and assign it. The SEs start it from Simulations." },
    ],
    links: [{ label: "Open Readiness", href: "/manager/team/readiness" }],
    related: ["mgr-se-workbench", "mgr-notifications", "mgr-roster"],
  },
  {
    id: "mgr-leaderboard",
    title: "Team leaderboard",
    summary: "See your team ranked by points from trophies, simulations and weekly practice streaks.",
    audience: ["manager"],
    category: "Team",
    keywords: ["leaderboard", "points", "rank", "streak", "trophies", "sim avg", "gamification"],
    overview: [
      "Team > Leaderboard lists the team highest points first, with columns for Rank, Trophies, Sim avg, Streak (weeks of practice) and Points.",
      "Points appear after simulations, challenges and trophies. Until then the page says there are no points yet.",
    ],
    steps: [
      { title: "Open the leaderboard", body: "Click Team, then Leaderboard." },
      { title: "Read the columns", body: "Compare Sim avg and Streak alongside Points to tell steady practice apart from one-off wins." },
      { title: "Follow up", body: "Open someone with a low streak from the Roster and assign a simulation from their workbench." },
    ],
    links: [{ label: "Open Leaderboard", href: "/manager/team/leaderboard" }],
    related: ["mgr-roster", "mgr-se-workbench"],
  },
  {
    id: "mgr-mentees",
    title: "Mentees and mentor check-ins",
    summary: "Respond to check-in requests from SEs you mentor and see which steps await manager sign-off.",
    audience: ["manager"],
    category: "Team",
    keywords: ["mentees", "mentor", "check-in", "mentor review", "approve step", "needs revision", "mentor notes"],
    overview: [
      "Team > Mentees covers SEs where you are the mentor on their ramp plan. The header shows \"Active mentees\", \"Check-ins pending\" and \"Awaiting manager sign-off\".",
      "\"Mentor reviews\" lists check-in requests from onboarding plans. A mentor's approval endorses a step; steps that need the manager still show \"Manager sign-off pending\".",
    ],
    steps: [
      { title: "Open Mentees", body: "Click Team, then Mentees." },
      { title: "Answer check-ins", body: "In \"Mentor reviews\", write \"Mentor feedback and next steps\" and click \"Approve step\" or \"Needs revision\"." },
      { title: "Check each mentee", body: "Under \"Your mentees\", expand a person to see their pending check-ins and anything awaiting sign-off." },
      { title: "Read mentor notes as a manager", body: "Mentor notes about your direct reports arrive in the Inbox as \"Mentor notes\" and in the SE's workbench under \"Mentor and notes\"." },
    ],
    links: [
      { label: "Open Mentees", href: "/manager/team/mentees" },
      { label: "Open Inbox", href: "/manager/inbox" },
    ],
    related: ["mgr-inbox", "mgr-se-workbench"],
  },
  {
    id: "mgr-coaching-cadence",
    title: "Coaching cadence",
    summary: "See who you haven't coached lately, on a 14-day rhythm, and the quality of your recent sign-offs.",
    audience: ["manager"],
    category: "Coaching",
    keywords: ["cadence", "coaching rhythm", "last coached", "urgent", "needs attention", "healthy", "coaching quality", "14 days"],
    overview: [
      "Coaching > Cadence lists your team \"most urgent first\" with Last coached, Open reviews, Focus, Status and Next action. Last coached is the date of your most recent reviewed sim card for that person.",
      "Urgent: they have open reviews, or you last coached them more than 21 days ago. Needs attention: never coached, more than 14 days since coaching, or readiness under 55. Everyone else is Healthy.",
      "\"Coaching quality, last 30 days\" summarises your structured sign-offs and flags fast rubber-stamping and cadence gaps.",
    ],
    steps: [
      { title: "Open Cadence", body: "Click Coaching, then Cadence." },
      { title: "Start with Urgent", body: "Clear any open reviews in the Inbox first; that alone moves people out of Urgent." },
      { title: "Book time", body: "Open a person and click \"Schedule 1:1\" to download an invite with talking points." },
      { title: "Check your quality", body: "Read the coaching quality panel and slow down if it flags rubber-stamping." },
    ],
    links: [{ label: "Open Cadence", href: "/manager/coaching" }],
    related: ["mgr-today", "mgr-se-workbench", "mgr-review-history"],
  },
  {
    id: "mgr-review-history",
    title: "Review history",
    summary: "See the reviews you have completed, newest first, and what you decided.",
    audience: ["manager"],
    category: "Coaching",
    keywords: ["history", "past reviews", "approved", "changes requested", "audit", "completed reviews"],
    overview: [
      "Coaching > Review history lists completed reviews, newest first, with the Item, the Decision (\"Approved\" or \"Changes requested\") and when it was Reviewed.",
    ],
    steps: [
      { title: "Open Review history", body: "Click Coaching, then Review history." },
      { title: "Scan decisions", body: "Use the Decision column to see what you approved and what you sent back." },
      { title: "Follow up", body: "For items sent back, check the SE's workbench under \"Sent back for changes\" to see whether they resubmitted." },
    ],
    links: [{ label: "Open Review history", href: "/manager/coaching/history" }],
    related: ["mgr-inbox", "mgr-review-workbench", "mgr-coaching-cadence"],
  },
  {
    id: "mgr-development",
    title: "Development plans and quarterly reviews",
    summary: "Track each SE's annual development goals and attest to quarterly reviews.",
    audience: ["manager"],
    category: "Coaching",
    keywords: ["development", "dev plan", "goals", "quarterly review", "attest", "attestation", "annual goals", "q1", "q4"],
    overview: [
      "Coaching > Development shows \"Plans that outlast the ramp\": each SE's annual goals and the quarterly attestations due. The header shows \"Plans\", \"Attestations due\" and \"Overdue\".",
      "\"Quarterly attestations due\" lists reviews due in the next 14 days, marked \"Due soon\" or \"Overdue\".",
      "A plan has at most 5 goals. Creating a plan schedules Q1 to Q4 reviews automatically. Goals show as Not started, On track, At risk or Achieved.",
    ],
    steps: [
      { title: "Open Development", body: "Click Coaching, then Development." },
      { title: "Attest due reviews", body: "In \"Quarterly attestations due\", click \"Attest\" next to a review to open it on that SE's plan." },
      { title: "Create a missing plan", body: "Under \"Goals by SE\", click \"Create plan\" for anyone without one, then add up to 5 goals." },
      { title: "Review an existing plan", body: "Click \"Open plan\" to see goals, evidence and this quarter's review status." },
    ],
    links: [
      { label: "Open Development", href: "/manager/coaching/development" },
      { label: "Open development plans", href: "/development" },
    ],
    related: ["mgr-coaching-cadence", "mgr-se-workbench"],
  },
  {
    id: "mgr-programs",
    title: "Programs: the list and the program workbench",
    summary: "See every ramp program, how your enrolled SEs are doing, and open a program to work on it.",
    audience: ["manager"],
    category: "Programs",
    keywords: ["programs", "ramp", "onboarding", "program workbench", "progress", "outline", "people", "schedule", "phases", "13 weeks"],
    overview: [
      "Programs > Programs (\"Every ramp in one place.\") shows \"Programs\", \"Avg completion\" and \"SEs at risk\", then one row per program.",
      "Each program runs 13 weeks in four phases: Foundations, Field skills, Advisory readiness and Certification.",
      "Opening a row opens the program workbench with four tabs: Progress, Outline, People and Schedule. Enablement admins edit the outline; managers see it read only.",
    ],
    steps: [
      { title: "Open Programs", body: "Click Programs in the left navigation." },
      { title: "Open a program", body: "Click a program row. The workbench opens on the Progress tab." },
      { title: "Read Progress", body: "Each enrolled SE has a status per phase and an Overall percentage. Click a row to see that person's journey." },
      { title: "Read the Outline", body: "Click Outline to see what every SE on this program works through, phase by phase, including gate steps." },
      { title: "Check the Schedule", body: "Click Schedule to see dated steps across the 13 weeks for everyone enrolled." },
    ],
    links: [{ label: "Open Programs", href: "/manager/programs" }],
    related: ["mgr-program-enroll", "mgr-program-journey", "mgr-plan-calendar"],
  },
  {
    id: "mgr-program-enroll",
    title: "Enrolling people in a program",
    summary: "Add SEs to a program with a start date and an optional mentor.",
    audience: ["manager"],
    category: "Programs",
    keywords: ["enroll", "assign plan", "add to program", "start date", "mentor", "ramp plan", "onboarding"],
    overview: [
      "You can only enroll people in a program whose outline you can see. People already on the program don't appear in the list.",
      "The target completion date is calculated from the start date and the length of the program's steps.",
    ],
    steps: [
      { title: "Open the People tab", body: "Open a program and click People, or click \"Enroll people\" on an empty Progress tab." },
      { title: "Pick people", body: "Under \"Enroll people\", tick each SE you want to add." },
      { title: "Set the start date", body: "Choose a \"Start date\". It defaults to today." },
      { title: "Choose a mentor", body: "Pick from \"Mentor (optional)\", or leave it as \"No mentor\"." },
      { title: "Enroll", body: "Click \"Enroll N\". You see how many people were enrolled; any failures are listed by name." },
      { title: "Remove someone", body: "In the Enrolled list, click Remove on their row and confirm. People with no progress come off the program." },
    ],
    links: [{ label: "Open Programs", href: "/manager/programs" }],
    related: ["mgr-programs", "mgr-program-journey", "mgr-se-workbench"],
  },
  {
    id: "mgr-program-journey",
    title: "Reading a person's journey: phase status, at risk and overdue",
    summary: "What each phase and step status means in a program, and when an SE counts as at risk.",
    audience: ["manager"],
    category: "Programs",
    keywords: ["journey", "phase status", "overdue", "at risk", "on track", "in progress", "upcoming", "complete", "in review"],
    overview: [
      "A step is overdue when its due date has passed and it hasn't been validated yet.",
      "Phase statuses: \"Complete\" (every step done), \"Overdue\" (any step in it is overdue), \"In progress\" (the first phase with work left), \"Upcoming\" (later phases) and \"No steps\".",
      "Enrollment health: \"Complete\" when every step is done, \"At risk\" when any step is overdue, \"On track\" once they've started, otherwise \"Not started\".",
      "Step statuses in the journey: Done, Overdue, In review, In progress and Not started.",
    ],
    steps: [
      { title: "Open the journey", body: "On a program's Progress tab, click a person's row." },
      { title: "Read the header", body: "You see when they started, their target date, Progress as a percentage and the Overdue count." },
      { title: "Scan the phases", body: "Each phase lists its steps with a status. Gate steps are marked \"Gate\"." },
      { title: "Act on it", body: "Click \"Coaching view\" to go to the coaching page for that person, or approve their waiting steps from the Inbox." },
    ],
    links: [{ label: "Open Programs", href: "/manager/programs" }],
    related: ["mgr-programs", "mgr-review-workbench", "mgr-plan-calendar"],
  },
  {
    id: "mgr-plan-calendar",
    title: "The plan Calendar",
    summary: "See ramp steps for your team on a timeline, month or team view, and shift dates by dragging.",
    audience: ["manager"],
    category: "Programs",
    keywords: ["calendar", "timeline", "gantt", "month", "team view", "drag", "reschedule", "block day", "scheduling check"],
    overview: [
      "Programs > Calendar shows your team's ramp plans. The \"Calendar view\" switch offers Timeline, Month and Team. The \"Calendar perspective\" switch lets you preview as Manager, SE or Mentor.",
      "In the Manager perspective you can change dates. Other perspectives are \"Read only.\"",
      "The \"Scheduling check\" strip flags conflicts, or says \"No issues found\".",
    ],
    steps: [
      { title: "Open the Calendar", body: "Click Programs, then Calendar." },
      { title: "Choose a view", body: "Pick Timeline for bars per step, Month for a calendar grid, or Team for one summary card per person." },
      { title: "Shift dates", body: "In Timeline, drag a bar, or focus it and use the arrow keys, to move its dates." },
      { title: "Save", body: "Click \"Save changes\" to keep your edits." },
      { title: "Block a day", body: "Click \"Block today\" to mark today as a blocked day on the calendar." },
    ],
    links: [{ label: "Open Calendar", href: "/plan-calendar" }],
    related: ["mgr-programs", "mgr-program-journey"],
  },
  {
    id: "mgr-certifications",
    title: "Certification sign-off",
    summary: "See who is ready for a certification gate and approve or request changes on their evidence.",
    audience: ["manager"],
    category: "Reviews",
    keywords: ["certification", "gate", "sign-off", "evidence", "approve", "request changes", "ready for sign-off", "cleared"],
    overview: [
      "Programs > Certifications (\"Who is ready to sign off.\") lists your team and their gate status. Open one SE to see their evidence matrix by gate.",
      "Approving clears the gate and notifies the SE. Requesting changes also notifies them. If you leave the notes empty, the SE sees \"Cleared for field readiness.\" or \"Needs more evidence before sign-off.\"",
      "Certification gates submitted for sign-off also appear in your Inbox under Gates, where they use the strictest sign-off tier.",
    ],
    steps: [
      { title: "Open Certifications", body: "Click Programs, then Certifications." },
      { title: "Open an SE", body: "Click the link next to a person to open their evidence matrix." },
      { title: "Review a gate", body: "Click \"Review\" on a gate that is ready for sign-off. Read the evidence and any attached file or link." },
      { title: "Decide", body: "Add notes if you want, then click \"Approve\" or \"Request changes\". The SE is notified either way." },
    ],
    links: [
      { label: "Open Certifications", href: "/certifications" },
      { label: "Open Inbox", href: "/manager/inbox" },
    ],
    related: ["mgr-review-workbench", "mgr-inbox"],
  },
  {
    id: "mgr-notifications",
    title: "Notifications and readiness nudges",
    summary: "Where notifications appear and why you get a nudge when an SE is critical on a readiness area.",
    audience: ["manager"],
    category: "Getting started",
    keywords: ["notifications", "bell", "alerts", "nudge", "critical", "readiness nudge", "mark all read", "unread"],
    overview: [
      "The Notifications bell shows an unread count. Open it to read notifications and use \"Mark all read\".",
      "Readiness nudges: when the readiness map is turned on for your organisation and you open Today, Roster or Readiness, the app checks each SE. If someone is critical on a readiness area, you get a notification titled \"<name> is critical on <area>\" and the SE gets one too. Both link to the recommended action.",
      "Nudges only cover each SE's single worst critical area, and at most once every 7 days for the same nudge. Nothing is assigned automatically.",
    ],
    steps: [
      { title: "Open notifications", body: "Click the Notifications bell. Unread items are counted at the top." },
      { title: "Follow a nudge", body: "Click the notification to go to the recommended action for that area." },
      { title: "Assign practice if needed", body: "Go to Team > Readiness and click \"Assign practice to N\" for that competency." },
      { title: "Clear the list", body: "Click \"Mark all read\" when you're done." },
    ],
    links: [{ label: "Open Readiness", href: "/manager/team/readiness" }],
    related: ["mgr-readiness", "mgr-today"],
  },
];
