import type { HelpArticle } from "@/lib/help/types";

/**
 * Help Center articles for sales engineers. Labels are quoted from the SE workspace UI.
 */
export const SE_ARTICLES: HelpArticle[] = [
  // ---------------------------------------------------------------- Getting started
  {
    id: "se-first-sign-in",
    title: "Sign in for the first time and set up MFA",
    summary: "Sign in with your work email, then enroll an authenticator app. You confirm a code on every sign-in.",
    audience: ["se"],
    category: "Getting started",
    keywords: ["login", "log in", "sign in", "mfa", "2fa", "two factor", "authenticator", "qr code", "verification code", "first time", "enroll"],
    overview: [
      "Signing in to SE Enablement takes two steps: your password, then a six-digit code from an authenticator app. MFA is required every time you sign in, not just on new devices.",
      "The first time you sign in, you'll be asked to enroll an authenticator. After that you go straight to the verify screen. If you're inactive for 15 minutes, your session expires and you have to sign in again.",
    ],
    steps: [
      { title: "Sign in with your work email", body: "On \"Welcome back.\", enter your \"Work email\" and \"Password\" and click \"Sign in\". If your company uses single sign-on, you may see \"Continue with SSO\" instead.", tip: "Only email addresses on your company's domain can sign in." },
      { title: "Scan the QR code", body: "On \"Set up your authenticator.\", scan the QR code with your authenticator app. If you can't scan it, use \"Can't scan? Enter this key\" to type the key in manually." },
      { title: "Activate MFA", body: "Type the code from your app into \"6-digit verification code\" and click \"Activate MFA\". You'll land on Today." },
      { title: "Verify on every later sign-in", body: "From now on, after your password you'll see \"Check your authenticator.\" Enter the \"Six-digit code\" and click \"Verify and continue\"." },
      { title: "Switch accounts if needed", body: "If you're signed in as the wrong person, click \"Use a different account\" on the verify screen to sign out and start over." },
    ],
    links: [{ label: "Open Today", href: "/dashboard" }],
    related: ["se-today", "se-change-password", "se-my-ramp-overview"],
  },
  {
    id: "se-today",
    title: "Use the Today page",
    summary: "Today shows your next ramp step, what's coming up, and your gate progress.",
    audience: ["se"],
    category: "Getting started",
    keywords: ["home", "dashboard", "today", "next step", "what's next", "due", "overdue", "coming up"],
    overview: [
      "Today is the first page you see after signing in. It's built around one card, your next ramp step, along with the week of your ramp you're in and what's coming after it.",
      "If a step is waiting on a reviewer, the card says \"Waiting\" and names the reviewer. Overdue steps show a red \"N days overdue\" pill.",
    ],
    steps: [
      { title: "Open Today", body: "Click \"Today\" in the navigation. The header shows the week of your ramp and whose turn the current step is, for example \"Step 4 is yours.\"" },
      { title: "Act on the next step", body: "Use the main button on the \"Next step\" card. Its label matches the step type, such as \"Open challenge\", \"Start simulation\", \"Review content\", \"Log shadow meeting\", \"Request mentor review\" or \"Open deal prep\". Click \"View criteria\" to see what counts as done." },
      { title: "Check what's coming up", body: "\"Coming up\" lists your next three steps. Steps marked \"Unlocks when the current gate clears\" can't start until the current gate is signed off." },
      { title: "Track your gates", body: "The gates card on the right shows your stamps. Click \"Submit evidence\" or \"View gates\" to go to Certification." },
    ],
    links: [
      { label: "Open Today", href: "/dashboard" },
      { label: "Open My ramp", href: "/my-plan" },
    ],
    related: ["se-my-ramp-overview", "se-submit-step", "se-certification"],
  },

  // ---------------------------------------------------------------- My ramp
  {
    id: "se-my-ramp-overview",
    title: "How your ramp works: phases, steps and gates",
    summary: "Your ramp is a 13-week plan in four phases, each closed by a gate that your mentor or manager signs off.",
    audience: ["se", "manager"],
    category: "My ramp",
    keywords: ["ramp", "onboarding", "plan", "program", "phases", "segments", "gates", "13 weeks", "locked", "validated", "calendar"],
    overview: [
      "A ramp runs 13 weeks across four phases: Foundations, Field skills, Advisory readiness and Certification. Each phase has steps of different types: Content, Challenge, Practice (simulation), Shadow, Review (mentor review), Deal prep and Task.",
      "Each phase ends with a gate. Your mentor or manager signs off the gate once the steps before it are validated, and that unlocks the next phase. If you miss a gate date, the gate moves later. Your progress is never reset.",
      "Step statuses are \"Not started\", \"In progress\", \"In review\", \"Validated\" and \"Locked\".",
    ],
    steps: [
      { title: "Open My ramp", body: "Click \"My ramp\" in the navigation. The header shows the current week, and the runway below it shows each phase and its weeks." },
      { title: "Find your current step", body: "In the current phase, the highlighted card marked \"Now\" is the step to work on. Click \"Start\" or \"Continue\", or \"Step details\" to read it first." },
      { title: "Scan the rest of the phase", body: "The table lists the remaining steps with \"Type\" and \"Due\". Gate rows are labeled \"Closes this segment\". Locked rows show \"Unlocks after segment N\" and can't be opened yet." },
      { title: "Switch to Calendar", body: "If your workspace has it turned on, use the \"List\" / \"Calendar\" toggle in the header to see your steps on their dates." },
      { title: "Review finished phases", body: "Completed phases collapse to show how many steps were validated. Click \"Show\" to expand one." },
    ],
    links: [
      { label: "Open My ramp", href: "/my-plan" },
      { label: "Calendar view", href: "/my-plan?view=calendar" },
    ],
    related: ["se-submit-step", "se-certification", "se-today"],
  },
  {
    id: "se-submit-step",
    title: "Open and submit a ramp step",
    summary: "Open a step, do the work, add your evidence, and submit it so your manager or mentor can validate it.",
    audience: ["se", "manager"],
    category: "My ramp",
    keywords: ["submit", "evidence", "step", "task", "complete", "review", "validated", "resubmit", "shadow log", "mentor review", "with reviewer"],
    overview: [
      "Each step page has a \"Done when\" checklist and an \"Evidence\" section. The checklist is there to help you check your own work. It doesn't stop you from submitting.",
      "Your manager validates most steps. Steps of type Review (mentor review) go to your mentor. While you wait, the step shows \"With reviewer\". If the reviewer asks for changes, the step reopens so you can resubmit.",
    ],
    steps: [
      { title: "Open the step", body: "In My ramp, click the step title or \"Step details\". The page shows \"Step N of M\", the step type and its due date." },
      { title: "Complete the work for the step type", body: "Content: click \"Open resource\", then fill in \"What did you learn?\". Shadow: fill in \"Shadow meeting log\". Review: enter a \"Topic for mentor discussion\". Task: describe it in \"What did you complete?\"." },
      { title: "Submit", body: "Click \"Submit for review\", \"Submit for mentor review\" or \"Submit for manager sign-off\", depending on the step. You'll return to My ramp." },
      { title: "Practice and deal prep steps", body: "For challenge and simulation steps, click \"Continue\". Your result from the practice tool is attached automatically. For deal prep steps, click \"Open deal prep\". Saving the brief submits the step." },
      { title: "Wait for validation", body: "The step shows \"In review\" until your reviewer acts on it. You get a notification when it's approved or sent back." },
    ],
    links: [{ label: "Open My ramp", href: "/my-plan" }],
    related: ["se-my-ramp-overview", "se-feedback", "se-who-sees-my-work"],
  },

  // ---------------------------------------------------------------- Practice
  {
    id: "se-practice-preflight",
    title: "Prepare for a real call with Pre-flight",
    summary: "Pre-flight builds a short checklist for an upcoming customer call from the other practice tools.",
    audience: ["se"],
    category: "Practice",
    keywords: ["practice", "pre-flight", "preflight", "call prep", "rehearse", "assigned practice", "checklist"],
    overview: [
      "Practice rounds are never scored. Only an attempt you submit reaches your manager.",
      "Pre-flight's plan has four parts: a Market Pulse refresher, a deal prep brief for the account, a simulation with your chosen audience, and a Flight Check.",
    ],
    steps: [
      { title: "Open Practice", body: "Click \"Practice\" in the navigation. The \"Pre-flight\" card is at the top of the page." },
      { title: "Enter the call details", body: "Fill in \"Account\" and \"Call date\", choose the audience you'll be meeting (for example \"CISO\" or \"Procurement lead\"), and click \"Build my pre-flight\"." },
      { title: "Work through your plan", body: "Under \"Your plan\", open each item. Click \"Mark done\" as you finish each one. When every item is done, you're cleared for the call." },
      { title: "Check what's assigned", body: "The \"Assigned to you\" rail lists challenges and simulations from your ramp or your manager, with due dates." },
    ],
    links: [{ label: "Open Pre-flight", href: "/practice" }],
    related: ["se-simulations", "se-deal-prep", "se-quizzes", "se-flight-check"],
  },
  {
    id: "se-simulations",
    title: "Run an AI buyer simulation",
    summary: "Role-play a call with an AI buyer, get a scored coaching card, then practice again or submit it to your manager.",
    audience: ["se", "manager"],
    category: "Practice",
    keywords: ["simulation", "role play", "roleplay", "mock call", "ai buyer", "persona", "coaching card", "score", "objection"],
    overview: [
      "The AI plays a buyer persona and starts the conversation as soon as the page opens. The scenario brief lists what you'll be scored on, for example \"Discovery\", \"Objection handling\", \"Executive storyline\" and \"Next step\".",
      "When you end the role-play, the AI writes a coaching report with a score out of 100, a strength, something to improve, a suggested next practice and a summary for your manager. Practice rounds stay private. Your manager only sees cards you submit.",
    ],
    steps: [
      { title: "Open Simulations", body: "Go to Practice, then \"Simulations\", or click \"Start simulation\" on a ramp step. Wait for the persona to open the conversation." },
      { title: "Hold the conversation", body: "Type your replies, or click \"Use microphone\" to speak them. The \"Live coaching\" rail suggests a next move after each reply.", tip: "Start a message with HINT: to ask for coaching mid-call." },
      { title: "End and get feedback", body: "Click \"End & get feedback\". The \"AI coaching report\" shows your score out of 100 and coaching notes." },
      { title: "Add a reflection", body: "Write at least a sentence in \"Your reflection\". You need a reflection before you can save or submit." },
      { title: "Practice again or submit", body: "Click \"Practice again\" to save this as a practice round, or \"Submit to manager\" to send the card for review." },
    ],
    links: [{ label: "Open Simulations", href: "/practice/simulations" }],
    related: ["se-practice-preflight", "se-feedback", "se-competencies"],
  },
  {
    id: "se-challenges",
    title: "Complete a challenge",
    summary: "Pick a hands-on challenge, do the work, and submit evidence for your manager to approve.",
    audience: ["se", "manager"],
    category: "Practice",
    keywords: ["challenge", "exercise", "lab build", "hands-on", "submission", "redo", "approved", "generate challenge"],
    overview: [
      "Challenges are hands-on tasks that your manager reviews. They don't get a numeric score. Your manager approves the work or sends it back with \"Redo requested\".",
      "The library has curated challenges and AI-generated ones, tagged \"Curated\" or \"AI\". You can filter by level, vertical and competency.",
    ],
    steps: [
      { title: "Open Challenges", body: "Go to Practice, then \"Challenges\". The \"Library\" view lists challenges you can take. Filter by level, vertical or competency, or change the sort." },
      { title: "Pick one", body: "Click \"Work on this challenge\" on the one you want. It becomes the challenge you'll submit evidence for." },
      { title: "Submit your evidence", body: "Upload a file or paste an evidence link, answer \"What did you learn? What would you do differently?\", and click \"Submit for review\"." },
      { title: "Track the result", body: "Open \"My submissions\" to see each one's status: \"Submitted\", \"Approved\" or \"Redo requested\". To redo one, update it and submit again." },
    ],
    links: [{ label: "Open Challenges", href: "/practice/challenges" }],
    related: ["se-feedback", "se-certification", "se-practice-preflight"],
  },
  {
    id: "se-pitch",
    title: "Record a pitch in Pitch Studio",
    summary: "Record a timed pitch, review it with AI coaching, then save it as practice or submit it for manager review.",
    audience: ["se", "manager"],
    category: "Practice",
    keywords: ["pitch", "pitch studio", "recording", "video", "talk track", "elevator pitch", "peer review", "rubric"],
    overview: [
      "Pitch Studio has two modes. \"Assigned queue\" is for pitches your manager reviews when you submit them. \"Free practice\" is private, and your manager isn't notified.",
      "After AI coaching, the rail shows rubric scores for \"Clarity & structure\", \"Value articulation\" and \"Confidence & pacing\". Your manager grades submitted pitches out of 5, and peers can review pitches in the library.",
    ],
    steps: [
      { title: "Open Pitch", body: "Go to Practice, then \"Pitch\". Choose \"Assigned queue\" or \"Free practice\" and pick a scenario." },
      { title: "Record", body: "Allow camera and microphone access, then use the record button to start and stop. Each scenario has a time limit. Click \"Discard\" to start over." },
      { title: "Reflect and get coaching", body: "Answer the reflection prompt, then click \"Get AI coaching\" for tips and rubric scores." },
      { title: "Save or submit", body: "Click \"Save practice\" to keep it private, or \"Submit for review\" to send it to your manager. Submitting requires an assigned queue slot." },
    ],
    links: [{ label: "Open Pitch Studio", href: "/practice/pitch" }],
    related: ["se-feedback", "se-who-sees-my-work"],
  },
  {
    id: "se-quizzes",
    title: "Take the Market Pulse quiz",
    summary: "A short weekly multiple-choice quiz on competitive intel, graded as soon as you submit.",
    audience: ["se"],
    category: "Practice",
    keywords: ["quiz", "quizzes", "market pulse", "competitive", "competitors", "weekly quiz", "knowledge check"],
    overview: [
      "Market Pulse is graded automatically. A score of 70% or higher is \"On track\", 60% or higher is \"Close\", and anything lower is \"Needs practice\".",
    ],
    steps: [
      { title: "Open Quizzes", body: "Go to Practice, then \"Quizzes\". This week's quiz is listed under \"Week of\" and that week's date." },
      { title: "Answer every question", body: "Pick an answer for each question. You can't submit until all of them are answered." },
      { title: "Submit and review", body: "Click \"Submit quiz\". You'll see your score, with your answer and the correct answer marked for each question." },
      { title: "Reinforce", body: "Use \"Reinforce with practice\" to open a related challenge, and \"Quick reference\" for competitor notes. \"Your history\" shows past weeks." },
    ],
    links: [{ label: "Open Market Pulse", href: "/practice/quizzes" }],
    related: ["se-flight-check", "se-practice-preflight"],
  },
  {
    id: "se-flight-check",
    title: "Find your gaps with Flight check",
    summary: "An adaptive check across five competencies that finds your weakest area and assigns practice for it.",
    audience: ["se"],
    category: "Practice",
    keywords: ["flight check", "assessment", "readiness check", "gaps", "adaptive", "field signal score"],
    overview: [
      "Flight check asks questions that get harder or easier based on your answers. It covers \"Discovery\", \"Objection handling\", \"Demo execution\", \"Competitive positioning\" and \"Value articulation\".",
      "At the end you get a \"Field signal score\". Practice for your weakest result is assigned to you automatically, so you don't have to choose.",
    ],
    steps: [
      { title: "Open Flight check", body: "Go to Practice, then \"Flight check\", and click \"Start flight check\". If you left one unfinished, click \"Resume last session\"." },
      { title: "Answer each question", body: "Choose an answer or write one in \"Your response\", then click \"Next question\". Click \"Skip\" to pass." },
      { title: "Watch your scores", body: "After each answer you'll see \"Signal strong\" or \"Gap detected\". \"Scores so far\" shows your score for each competency." },
      { title: "Go practice", body: "When you finish, review your Field signal score and click \"Go practice\" to start the practice assigned to you." },
    ],
    links: [{ label: "Open Flight check", href: "/practice/flight-check" }],
    related: ["se-competencies", "se-quizzes"],
  },
  {
    id: "se-deal-prep",
    title: "Build a deal prep brief",
    summary: "Generate an AI brief for a customer call with discovery questions, likely objections, competitive positioning and risks.",
    audience: ["se", "manager"],
    category: "Practice",
    keywords: ["deal prep", "account prep", "brief", "call prep", "objections", "discovery questions", "stakeholder map", "debrief"],
    overview: [
      "Deal prep briefs aren't scored. They're private to you unless you share one with your manager or save it to a ramp step.",
    ],
    steps: [
      { title: "Open Deal prep", body: "Go to Practice, then \"Deal prep\", or click \"Open deal prep\" on a ramp step." },
      { title: "Describe the deal", body: "Under \"Build your brief\", fill in fields such as \"Account name\", \"Industry\", \"Deal stage\", \"Meeting type\", \"Competitors\" and \"Context\". Then click \"Generate brief\"." },
      { title: "Use the brief", body: "Read the sections, from \"Discovery questions\" and \"Likely objections\" through \"Risk flags\" and \"Stakeholder map\". Click \"Practice\" next to an objection to rehearse it with the AI buyer." },
      { title: "Refine or export", body: "Use \"Regenerate with a focus\" (for example \"Make objections harder\"), \"Copy brief\" or \"Export PDF\"." },
      { title: "Share and debrief", body: "Click \"Share brief with manager for review\" to send it to your manager's inbox. After the call, record the outcome and click \"Save debrief\"." },
    ],
    links: [{ label: "Open Deal prep", href: "/practice/deal-prep" }],
    related: ["se-practice-preflight", "se-isc-lab", "se-submit-step"],
  },

  // ---------------------------------------------------------------- Readiness
  {
    id: "se-competencies",
    title: "Check your competencies",
    summary: "Readiness shows where you stand on each competency, based on your scored practice.",
    audience: ["se", "manager"],
    category: "Readiness",
    keywords: ["readiness", "competencies", "skills", "gaps", "progress", "four-week change", "on track"],
    overview: [
      "Your competencies appear after your first scored simulation or reviewed challenge. Each one is rated \"Needs practice\", \"Close\" or \"On track\", with its change over the last four weeks.",
    ],
    steps: [
      { title: "Open Readiness", body: "Click \"Readiness\" in the navigation. You'll land on the \"Competencies\" tab." },
      { title: "Read your table", body: "Check each competency's status and \"Four-week change\". If a competency doesn't have enough history yet, it shows \"No change data yet\"." },
      { title: "Close a gap", body: "For anything marked \"Needs practice\", run a simulation, a challenge or a Flight check to add new evidence." },
    ],
    links: [{ label: "Open Competencies", href: "/readiness" }],
    related: ["se-flight-check", "se-feedback", "se-growth-plan"],
  },
  {
    id: "se-feedback",
    title: "Read and act on feedback",
    summary: "The Feedback tab collects your reviewers' grades and comments on your challenges and simulations.",
    audience: ["se"],
    category: "Readiness",
    keywords: ["feedback", "comments", "grades", "review", "needs revision", "redo", "reminder", "awaiting manager"],
    overview: [
      "Reviewers grade work as \"Below bar\", \"Close\" or \"At bar\", with a score out of 5. Some items have only a grade and no written comment.",
    ],
    steps: [
      { title: "Open Feedback", body: "Go to Readiness, then \"Feedback\". The number on the tab is how many items you have." },
      { title: "Filter the list", body: "Choose \"All\", \"Needs action\", \"Awaiting manager\" or \"Approved\"." },
      { title: "Act on an item", body: "For work that needs changes, click \"Resubmit challenge\" or \"Re-run simulation\". Click \"View details\" or \"View plan step\" for the full context." },
      { title: "Nudge your manager", body: "If an item has been sitting in \"Awaiting manager\", click \"Send your manager a reminder email\". You can send one reminder every 7 days." },
    ],
    links: [{ label: "Open Feedback", href: "/readiness/feedback" }],
    related: ["se-challenges", "se-simulations", "se-growth-plan"],
  },
  {
    id: "se-growth-plan",
    title: "Follow your growth plan",
    summary: "Your growth plan holds annual development goals that you check in on with your manager each quarter.",
    audience: ["se", "manager"],
    category: "Readiness",
    keywords: ["growth plan", "development plan", "goals", "idp", "career", "quarterly review", "check-in"],
    overview: [
      "Your manager builds your growth plan, starting from AI-suggested goals. Until it's ready you'll see \"Your growth plan is being built\", and you'll be notified when it's done.",
      "Goals are tracked as \"Not started\", \"In progress\", \"On track\", \"At risk\" or \"Achieved\", with a check-in with your manager each quarter.",
    ],
    steps: [
      { title: "Open Growth plan", body: "Go to Readiness, then \"Growth plan\"." },
      { title: "Review your goals", body: "Look at each goal's status. Anything listed under \"Action needed\" or flagged \"Behind\" needs attention first." },
      { title: "Prepare for check-ins", body: "Before your quarterly check-in, collect evidence of progress on each goal, such as challenges, simulations or deal work, so you can go through it with your manager." },
    ],
    links: [{ label: "Open Growth plan", href: "/readiness/growth-plan" }],
    related: ["se-competencies", "se-feedback"],
  },
  {
    id: "se-certification",
    title: "Submit certification evidence for a gate",
    summary: "Each certification gate needs written evidence that you submit and your manager signs off.",
    audience: ["se", "manager"],
    category: "Readiness",
    keywords: ["certification", "certify", "gate", "evidence", "sign off", "sign-off", "cleared", "stamps", "field ready"],
    overview: [
      "Certification works one gate at a time. Gate statuses are \"Locked\", \"Not started\", \"In progress\", \"Ready\", \"Submitted\" and \"Cleared\". The evidence table shows the simulations and challenges that usually support each gate, but missing ones never block you from submitting.",
      "When you submit, the gate goes to your manager for sign-off. If they approve it, the gate is cleared and you're notified. If they request changes, you're notified too.",
    ],
    steps: [
      { title: "Open Certification", body: "Go to Readiness, then \"Certification\", or click \"Submit evidence\" on the gates card on Today." },
      { title: "Check the gate", body: "In \"Certification evidence by gate\", review the \"Sims\", \"Challenge\", \"Evidence\" and \"Sign-off\" columns for the gate you're working on." },
      { title: "Write your evidence", body: "Click \"Submit evidence\". Describe the account, who was in the room and the outcome, using at least 20 characters. You can also add a link or upload a file." },
      { title: "Submit for sign-off", body: "Click \"Submit for sign-off\". The gate shows \"Submitted\" until your manager reviews it, then \"Cleared\" once it's approved." },
    ],
    links: [{ label: "Open Certification", href: "/readiness/certification" }],
    related: ["se-my-ramp-overview", "se-who-sees-my-work", "se-challenges"],
  },

  // ---------------------------------------------------------------- Learn
  {
    id: "se-learn-library",
    title: "Find content in the Learn library",
    summary: "Search modules, battle cards, demo guides, one-pagers and playbooks, and track your learning path.",
    audience: ["se"],
    category: "Learn",
    keywords: ["learn", "library", "resources", "content", "training", "battle cards", "demo guides", "playbooks", "modules", "release training", "learning path"],
    steps: [
      { title: "Open Learn", body: "Click \"Learn\" in the navigation. The \"Library\" opens first." },
      { title: "Search or filter", body: "Type in the search box to search modules, battle cards and demo guides, or filter by type, such as \"Modules\", \"Battle cards\", \"Demo guides\", \"One-pagers\" or \"Playbooks\"." },
      { title: "Continue your learning", body: "Under \"Your learning\", click \"Resume\" or \"Start\". \"Your release training\" and \"Picked for your ramp\" show content chosen for you." },
      { title: "Mark it complete", body: "When you finish a module, click \"Mark complete\". If something is wrong with the content, click \"Report a problem\"." },
    ],
    links: [{ label: "Open Library", href: "/learn" }],
    related: ["se-isc-lab", "se-quizzes"],
  },
  {
    id: "se-isc-lab",
    title: "Ask the ISC Lab AI coach",
    summary: "An AI coach grounded in docs, battle cards and peer pitches. Every answer cites its sources.",
    audience: ["se"],
    category: "Learn",
    keywords: ["isc lab", "lab", "ai coach", "ask", "chat", "battlecard", "objection", "account prep", "sources"],
    overview: [
      "ISC Lab answers questions using product docs, developer docs, the website, battle cards and peer pitches. Every answer lists its \"Sources consulted\" so you can check them.",
    ],
    steps: [
      { title: "Open ISC Lab", body: "Go to Learn, then \"ISC Lab\"." },
      { title: "Pick a mode", body: "Choose \"Ask ISC\", \"Account prep\" (enter an account name), \"Battlecard\" or \"Voice objection\". Use a prompt under \"Try one\" if you're not sure where to start." },
      { title: "Ask and check sources", body: "Type your question and press Enter (Shift+Enter adds a new line). Check the \"Sources consulted\" under the answer." },
      { title: "Save useful answers", body: "Save an answer to Deal Prep to use it in a brief." },
    ],
    links: [{ label: "Open ISC Lab", href: "/learn/lab" }],
    related: ["se-learn-library", "se-deal-prep"],
  },

  // ---------------------------------------------------------------- Account
  {
    id: "se-change-password",
    title: "View your account and change your password",
    summary: "Your account page shows your ramp progress, trophies and manager. You can change your password from it after re-verifying MFA.",
    audience: ["se"],
    category: "Account",
    keywords: ["account", "profile", "password", "change password", "reset password", "security", "trophy case", "milestones", "badges"],
    overview: [
      "Your account page has \"Ramp progress\", a \"Trophy case\" of every challenge and simulation your manager has approved, \"Career milestones\", \"Your manager\" and \"Security\".",
      "To change your password, you have to enter a new authenticator code first. Your new password must be at least 8 characters. If you've forgotten your password, use \"Forgot password?\" on the sign-in page instead.",
    ],
    steps: [
      { title: "Open your account", body: "Go to your account page. The header reads \"Your account\"." },
      { title: "Start a password change", body: "In \"Security\", click \"Change password\"." },
      { title: "Verify MFA", body: "In \"Step 1 of 2\", enter a fresh code from your authenticator." },
      { title: "Set the new password", body: "In \"Step 2 of 2\", fill in \"New password\" and \"Confirm new password\", then click \"Update password\". You'll see \"Password updated.\"" },
    ],
    links: [
      { label: "Open your account", href: "/account" },
      { label: "Change password", href: "/account/change-password" },
    ],
    related: ["se-first-sign-in", "se-who-sees-my-work"],
  },
  {
    id: "se-who-sees-my-work",
    title: "Who can see your work",
    summary: "Your manager reviews what you submit and your mentor reviews mentor steps. Practice rounds stay private.",
    audience: ["se", "manager"],
    category: "Account",
    keywords: ["privacy", "visibility", "manager", "mentor", "who sees", "private", "reviewer", "admin"],
    overview: [
      "Your manager is listed under \"Your manager\" on your account page. They validate your ramp steps, approve challenges, review simulation cards and pitches that you submit, sign off certification gates and build your growth plan.",
      "Your mentor reviews steps of type Review (mentor review) and can sign off gates. If you don't have a mentor, those requests go to your manager. Program admins can see every SE in the workspace.",
      "Some work stays private: simulation practice rounds, \"Free practice\" pitches and deal prep briefs you haven't shared.",
    ],
    steps: [
      { title: "Check who your manager is", body: "Open your account page and look under \"Your manager\". If it says no manager is assigned, contact your program admin." },
      { title: "Choose what to share", body: "Use \"Practice again\" or \"Save practice\" to keep work private. Use a submit button only when you want it reviewed." },
    ],
    links: [{ label: "Open your account", href: "/account" }],
    related: ["se-submit-step", "se-certification", "se-simulations"],
  },
];
