import type { ChallengeLibraryEntry } from "@/lib/challenges/challenge-library-types";

type ChallengeSeed = {
  n: number;
  level: ChallengeLibraryEntry["targetLevel"];
  difficulty: ChallengeLibraryEntry["difficulty"];
  title: string;
  description: string;
  steps: [string, string, string];
  success: [string, string, string];
  minutes: number;
  solutions: string[];
  competencies: string[];
};

const BATCH_PREFIX = "e5000002-0005-5000-8000";

function entry(seed: ChallengeSeed): ChallengeLibraryEntry {
  return {
    id: `${BATCH_PREFIX}-${String(seed.n).padStart(12, "0")}`,
    targetLevel: seed.level,
    title: seed.title,
    description: seed.description,
    steps: [...seed.steps],
    successCriteria: [...seed.success],
    estimatedMinutes: seed.minutes,
    linkedResources: ["https://developer.sailpoint.com/docs/"],
    linkedSolutions: seed.solutions,
    difficulty: seed.difficulty,
    competencyNames: seed.competencies,
  };
}

const AGENTIC_SEEDS: ChallengeSeed[] = [
  { n: 1, level: "Basic", difficulty: "foundational", title: "GenAI vs Agentic: Customer-Ready Definitions", minutes: 35, solutions: ["AIS", "Agentic Fabric"], competencies: ["Agentic Fabric", "AI Agents"], description: "Explain GenAI, agents, and agentic systems without jargon — foundational for every AIS conversation.", steps: ["Write 3-sentence definitions for GenAI, agent, agentic fabric.", "Give one healthcare and one SLED example each.", "Record 90-second elevator version."], success: ["Definitions accurate.", "Examples vertical-specific.", "Elevator version clear."] },
  { n: 2, level: "Basic", difficulty: "foundational", title: "Machine Account Inventory Discovery", minutes: 45, solutions: ["Machine Identity Security"], competencies: ["Machine Accounts"], description: "Help customer discover service principals, API keys, and bots they did not know existed.", steps: ["List five machine identity types in ISC.", "Run Search query for stale service accounts in lab.", "Draft discovery workshop agenda."], success: ["Five types named.", "Search query documented.", "Agenda time-boxed."] },
  { n: 3, level: "Senior", difficulty: "intermediate", title: "AIS: Non-Human Identity Lifecycle", minutes: 55, solutions: ["AIS"], competencies: ["AI Agents", "Machine Accounts"], description: "Map joiner-mover-leaver for AI agents and service principals.", steps: ["Diagram lifecycle for one copilot-style agent.", "Identify certification owner.", "Contrast with human joiner workflow."], success: ["Diagram complete.", "Owner assigned.", "Contrast accurate."] },
  { n: 4, level: "Senior", difficulty: "intermediate", title: "Agentic Fabric: Architecture Whiteboard", minutes: 60, solutions: ["Agentic Fabric"], competencies: ["Agentic Fabric"], description: "Whiteboard how Agentic Fabric sits between agents, MCP servers, and governance policy.", steps: ["Draw three-layer architecture.", "Label data flows and policy enforcement points.", "Record 5-minute explanation."], success: ["Layers labeled.", "Policy points clear.", "Recording coherent."] },
  { n: 5, level: "Advisory", difficulty: "advanced", title: "Board-Level AI Identity Risk Brief", minutes: 90, solutions: ["AIS", "Agentic Fabric"], competencies: ["Executive Demo Storytelling", "Agentic Fabric"], description: "Prepare 8-slide board narrative on AI identity risk for a Fortune 500 CISO.", steps: ["Define top 3 risks with business impact.", "Map SailPoint capabilities per risk.", "Include one customer reference pattern."], success: ["Risks business-framed.", "Capabilities mapped.", "Reference plausible."] },
  { n: 6, level: "Basic", difficulty: "intermediate", title: "MCP Server Governance 101", minutes: 50, solutions: ["MCP Governance"], competencies: ["Agentic Fabric"], description: "Explain why MCP servers need identity governance when agents call tools.", steps: ["Define MCP in customer language.", "List three governance gaps without SailPoint.", "Demo or diagram allow-list pattern."], success: ["MCP explained simply.", "Gaps specific.", "Allow-list shown."] },
  { n: 7, level: "Senior", difficulty: "advanced", title: "Shadow AI Discovery Playbook", minutes: 65, solutions: ["Agentic Fabric"], competencies: ["Agentic Fabric", "AI Agents"], description: "Operational playbook to find unsanctioned AI tools and agents in enterprise.", steps: ["List five discovery signals.", "Map to ISC Search or integrations.", "30-day remediation timeline."], success: ["Signals actionable.", "ISC mapping realistic.", "Timeline phased."] },
  { n: 8, level: "Basic", difficulty: "foundational", title: "OAuth vs PAT for Machine Auth", minutes: 40, solutions: ["Machine Identity Security"], competencies: ["Machine Accounts"], description: "Compare OAuth client credentials vs PAT for service-to-service — common SE confusion.", steps: ["Write comparison table.", "Recommend pattern for CI/CD pipeline.", "Note rotation and audit implications."], success: ["Table accurate.", "CI/CD recommendation sound.", "Rotation addressed."] },
  { n: 9, level: "Senior", difficulty: "intermediate", title: "Agent Certification Campaign Design", minutes: 55, solutions: ["AIS", "Certifications"], competencies: ["AI Agents", "Governance"], description: "Design certification campaign for high-privilege agents quarterly.", steps: ["Define certifier role for agents.", "Set scope and risk criteria.", "Write notification template."], success: ["Certifier defined.", "Scope risk-based.", "Template professional."] },
  { n: 10, level: "Advisory", difficulty: "advanced", title: "Competitive: Microsoft Agent Governance", minutes: 75, solutions: ["AIS"], competencies: ["Competitive Positioning", "AI Agents"], description: "Position SailPoint vs Microsoft Entra agent features without FUD.", steps: ["Build honest capability matrix.", "Three landmines and responses.", "Roleplay recording 5 min."], success: ["Matrix fair.", "Responses specific.", "Roleplay delivered."] },
  { n: 11, level: "Basic", difficulty: "intermediate", title: "Agent Identity in Access Request Catalog", minutes: 45, solutions: ["AIS", "Access Requests"], competencies: ["AI Agents"], description: "Show how agents appear in access catalog and approval flows.", steps: ["Configure or diagram agent access profile.", "Walk approval path.", "Explain auditor view."], success: ["Profile configured.", "Approval path clear.", "Audit view described."] },
  { n: 12, level: "Senior", difficulty: "advanced", title: "Zero Standing Privilege for Agents", minutes: 70, solutions: ["AIS"], competencies: ["AI Agents", "Machine Accounts"], description: "Design just-in-time elevation for autonomous agents.", steps: ["Define standing vs JIT for one agent.", "Workflow or policy sketch.", "Risk exceptions documented."], success: ["JIT defined.", "Sketch implementable.", "Exceptions bounded."] },
  { n: 13, level: "Basic", difficulty: "foundational", title: "Human vs Machine Identity Taxonomy", minutes: 35, solutions: ["ISC", "AIS"], competencies: ["Machine Accounts"], description: "Customer workshop slide: one slide taxonomy of identity types.", steps: ["Create taxonomy with 8+ types.", "Map each to ISC/AIS feature.", "Peer review with another SE."], success: ["Eight or more identity types listed.", "Feature mapping correct.", "Peer feedback incorporated."] },
  { n: 14, level: "Senior", difficulty: "intermediate", title: "Agentic Workflow: Agent Onboarding", minutes: 60, solutions: ["Workflows", "AIS"], competencies: ["ISC Workflows and Forms", "AI Agents"], description: "Build workflow that provisions new AI agent with scoped entitlements.", steps: ["Trigger on agent registration event.", "Approval by AI governance council.", "Provision and log evidence."], success: ["Trigger correct.", "Approval realistic.", "Evidence logged."] },
  { n: 15, level: "Advisory", difficulty: "advanced", title: "AI Governance Operating Model", minutes: 85, solutions: ["Agentic Fabric"], competencies: ["Agentic Fabric", "Executive Demo Storytelling"], description: "Draft RACI for AI identity governance across security, IT, and lines of business.", steps: ["RACI for 6 activities.", "Escalation path for rogue agent.", "Present to mock steering committee."], success: ["RACI complete.", "Escalation clear.", "Presentation executive-ready."] },
  { n: 16, level: "Basic", difficulty: "intermediate", title: "Service Principal Sprawl Assessment", minutes: 50, solutions: ["Machine Identity Security"], competencies: ["Machine Accounts"], description: "Quantify service principal sprawl using Search and recommend cleanup.", steps: ["Run sprawl queries in lab.", "Categorize by risk.", "Prioritized cleanup list."], success: ["Queries documented.", "Risk categories sensible.", "Priorities justified."] },
  { n: 17, level: "Senior", difficulty: "advanced", title: "Multi-Agent Orchestration Governance", minutes: 70, solutions: ["Agentic Fabric"], competencies: ["Agentic Fabric", "AI Agents"], description: "Govern chains where Agent A delegates to Agent B — delegation policy design.", steps: ["Diagram delegation chain.", "Policy enforcement points.", "Failure mode analysis."], success: ["Chain diagrammed.", "Enforcement identified.", "Failures addressed."] },
  { n: 18, level: "Basic", difficulty: "foundational", title: "AIS Demo Storyline: 5 Minutes", minutes: 40, solutions: ["AIS"], competencies: ["AI Agents", "Executive Demo Storytelling"], description: "Script tight AIS demo for identity-aware AI workshop.", steps: ["Write minute-by-minute script.", "Identify three wow moments.", "Record dry run."], success: ["Script timed.", "Wow moments clear.", "Dry run completed."] },
  { n: 19, level: "Senior", difficulty: "intermediate", title: "Entra Agent vs SailPoint AIS Objection", minutes: 45, solutions: ["AIS"], competencies: ["Competitive Positioning", "AI Agents"], description: "Handle 'Entra already does agents' with discovery-first response.", steps: ["Write discovery questions.", "Capability gap narrative.", "Practice 3-minute response."], success: ["Questions open-ended.", "Gaps factual.", "Response practiced."] },
  { n: 20, level: "Advisory", difficulty: "advanced", title: "Agentic Fabric ROI Model", minutes: 80, solutions: ["Agentic Fabric"], competencies: ["Agentic Fabric", "Executive Demo Storytelling"], description: "Build ROI model for Agentic Fabric — breach avoidance and audit efficiency.", steps: ["Three value drivers quantified.", "Assumptions table.", "One-page CFO summary."], success: ["Drivers quantified.", "Assumptions explicit.", "CFO summary crisp."] },
  { n: 21, level: "Basic", difficulty: "intermediate", title: "API Key Rotation Workflow", minutes: 50, solutions: ["Machine Identity Security", "Workflows"], competencies: ["Machine Accounts", "ISC Workflows and Forms"], description: "Automate API key rotation reminders and revocation.", steps: ["Design workflow triggers.", "Notification and escalation.", "Test in lab."], success: ["Triggers defined.", "Escalation path.", "Lab evidence."] },
  { n: 22, level: "Senior", difficulty: "intermediate", title: "Clinical AI Agent: HIPAA Scenario", minutes: 55, solutions: ["AIS"], competencies: ["AI Agents"], description: "Healthcare scenario: govern Epic-integrated clinical AI agent access.", steps: ["Map PHI touchpoints.", "Certification and audit requirements.", "Talk track for CISO."], success: ["PHI mapped.", "Audit requirements cited.", "Talk track HIPAA-aware."] },
  { n: 23, level: "Senior", difficulty: "advanced", title: "FED: AI Agent ATO Considerations", minutes: 65, solutions: ["AIS"], competencies: ["AI Agents", "Governance"], description: "Discuss ATO implications when agencies deploy autonomous agents.", steps: ["List NIST AI RMF touchpoints.", "Map to SailPoint controls.", "Brief for Fed IAM lead."], success: ["NIST references accurate.", "Control mapping plausible.", "Brief concise."] },
  { n: 24, level: "Basic", difficulty: "foundational", title: "Agent Naming and Metadata Standards", minutes: 35, solutions: ["AIS"], competencies: ["AI Agents"], description: "Propose metadata schema for agent identities in catalog.", steps: ["Define required attributes.", "Example for three agent types.", "Governance benefit statement."], success: ["Attributes complete.", "Examples varied.", "Benefits business-framed."] },
  { n: 25, level: "Advisory", difficulty: "advanced", title: "Agentic Fabric Reference Architecture", minutes: 90, solutions: ["Agentic Fabric"], competencies: ["Agentic Fabric"], description: "Publish internal reference architecture doc for field SEs.", steps: ["Components and integrations.", "Deployment patterns small vs large.", "FAQ for top 5 objections."], success: ["Architecture complete.", "Patterns differentiated.", "FAQ battle-tested."] },
];

export const SAILPOINT_CHALLENGE_LIBRARY_BATCH5: ChallengeLibraryEntry[] = AGENTIC_SEEDS.map(entry);
