import type { ChallengeLibraryEntry } from "@/lib/challenges/challenge-library-types";

export const SAILPOINT_CHALLENGE_LIBRARY_BATCH2: ChallengeLibraryEntry[] = [
  {
    id: "d4000001-0004-4000-8000-000000000001",
    targetLevel: "Basic",
    title: "Access Request: End-to-End Lab Walkthrough",
    description:
      "Trace a standard access request from catalog selection through approval to provisioning. Basic SEs must explain this flow clearly before customer demos of self-service access.",
    steps: [
      "Submit an access request in your lab tenant for a low-risk entitlement and capture each approval stage.",
      "Document which sources receive provisioning actions and expected SLA timing from ISC documentation.",
      "Record a three-minute talk track explaining business value to an IT helpdesk manager.",
    ],
    successCriteria: [
      "Evidence shows request ID, approver chain, and final provisioned state.",
      "Explanation distinguishes access profiles, entitlements, and roles accurately.",
      "Talk track mentions audit trail and least-privilege outcomes.",
    ],
    estimatedMinutes: 40,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/access/request_access.html"],
    linkedSolutions: ["Identity Security Cloud", "Access Requests"],
    difficulty: "foundational",
    competencyNames: ["ISC Workflows and Forms"],
  },
  {
    id: "d4000001-0004-4000-8000-000000000002",
    targetLevel: "Basic",
    title: "Identity Profile Correlation 101",
    description:
      "Explain how ISC correlates accounts from multiple sources onto a single identity. This foundational skill prevents mis-scoped demos and bad architecture advice in discovery.",
    steps: [
      "Pick one identity with accounts on at least two sources in your lab tenant.",
      "Screenshot correlation attributes and authoritative source settings for each contributing source.",
      "Write answers to: what happens on attribute conflict, and how would a duplicate identity appear?",
    ],
    successCriteria: [
      "Screenshots label authoritative vs non-authoritative sources correctly.",
      "Conflict explanation references identity profile mapping behavior.",
      "Duplicate scenario includes remediation path (manual correlation or rule).",
    ],
    estimatedMinutes: 45,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/provisioning/identity_profiles.html"],
    linkedSolutions: ["Identity Security Cloud", "Identity Profiles"],
    difficulty: "foundational",
    competencyNames: ["Entra ID / AD Connectors"],
  },
  {
    id: "d4000001-0004-4000-8000-000000000003",
    targetLevel: "Basic",
    title: "Concat Transform for Display Name",
    description:
      "Build a simple nested transform that produces a consistent display name from first and last name attributes — a common provisioning hygiene task.",
    steps: [
      "Author JSON for a Concat transform combining givenName and sn with a space separator.",
      "Optionally nest a Lower transform and document the final JSON structure.",
      "Apply to a lab identity profile mapping and preview results for three identities.",
    ],
    successCriteria: [
      "Transform JSON validates against SailPoint transform syntax (name, type, attributes).",
      "Preview shows consistent formatting across test identities.",
      "Notes explain when explicit input is required vs implicit input.",
    ],
    estimatedMinutes: 50,
    linkedResources: ["https://developer.sailpoint.com/docs/extensibility/transforms/"],
    linkedSolutions: ["Identity Security Cloud", "Transforms"],
    difficulty: "intermediate",
    competencyNames: ["ISC Workflows and Forms"],
  },
  {
    id: "d4000001-0004-4000-8000-000000000004",
    targetLevel: "Basic",
    title: "Certification Campaign Observer Brief",
    description:
      "Understand certification campaigns from the reviewer and auditor perspective. SEs field many questions about access review cycles during QBRs.",
    steps: [
      "Open an active or sample certification campaign and document certifier, scope, and due date.",
      "Complete (or simulate) three certification decisions and capture audit log entries.",
      "Summarize in one page how this maps to SOX/audit questions a customer CISO would ask.",
    ],
    successCriteria: [
      "Campaign summary includes scope, certifier role, and remediation path for rejections.",
      "Audit evidence shows decision timestamps and actors.",
      "CISO summary ties to risk reduction, not feature checklist.",
    ],
    estimatedMinutes: 45,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/certifications/certifications.html"],
    linkedSolutions: ["Identity Security Cloud", "Certifications"],
    difficulty: "foundational",
    competencyNames: ["ISC Workflows and Forms"],
  },
  {
    id: "d4000001-0004-4000-8000-000000000005",
    targetLevel: "Basic",
    title: "Entra ID Aggregation Timing Explainer",
    description:
      "Customers frequently ask how quickly ISC reflects Entra ID changes. Build an accurate aggregation and provisioning timing narrative backed by your lab.",
    steps: [
      "Review Entra ID source schedule, aggregation frequency, and correlation settings in Admin.",
      "Make a controlled attribute change in Entra (or document expected timing from docs if lab-limited).",
      "Produce a customer email template explaining expected propagation timing and what to check when 'it's not updating'.",
    ],
    successCriteria: [
      "Explainer references aggregation schedule, not instantaneous sync myths.",
      "Troubleshooting section lists authoritative source, correlation, and task queue checks.",
      "Email tone is appropriate for a customer IT director audience.",
    ],
    estimatedMinutes: 40,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/setup/entra.html"],
    linkedSolutions: ["Identity Security Cloud", "Entra ID connector"],
    difficulty: "foundational",
    competencyNames: ["Entra ID / AD Connectors"],
  },
  {
    id: "d4000001-0004-4000-8000-000000000006",
    targetLevel: "Basic",
    title: "Reference Transform Reuse Pattern",
    description:
      "Learn the SailPoint best practice of encapsulating repeated transform logic in a standalone Reference transform instead of copy-pasting JSON blocks.",
    steps: [
      "Create a base transform (e.g., normalize department codes) and save via POST /transforms.",
      "Create a second transform that references the first using the reference type.",
      "Document before/after maintainability benefits for a customer admin audience.",
    ],
    successCriteria: [
      "Two transforms exist with reference linkage shown in JSON.",
      "Explanation covers DRY principle and change-management benefits.",
      "Evidence includes successful identity or account preview using referenced transform.",
    ],
    estimatedMinutes: 55,
    linkedResources: ["https://developer.sailpoint.com/docs/extensibility/transforms/"],
    linkedSolutions: ["Identity Security Cloud", "Transforms"],
    difficulty: "intermediate",
    competencyNames: ["ISC Workflows and Forms"],
  },
  {
    id: "d4000001-0004-4000-8000-000000000007",
    targetLevel: "Basic",
    title: "Roles vs Access Profiles Customer FAQ",
    description:
      "Produce a one-page FAQ that helps customers understand when to use roles versus access profiles in ISC — a top-10 Basic SE discovery question.",
    steps: [
      "Draft five customer questions (e.g., 'Can a role replace AD groups?') with concise answers grounded in ISC docs.",
      "Include one Mermaid or simple diagram showing role composition → access profile → entitlements.",
      "Peer-review with another SE and incorporate one clarification.",
    ],
    successCriteria: [
      "FAQ answers are technically accurate for ISC (not IIQ legacy assumptions).",
      "Diagram shows direction of access assignment flow correctly.",
      "Language avoids internal-only jargon without definition.",
    ],
    estimatedMinutes: 35,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/provisioning/access_profiles.html"],
    linkedSolutions: ["Identity Security Cloud", "Roles", "Access Profiles"],
    difficulty: "foundational",
  },
  {
    id: "d4000001-0004-4000-8000-000000000008",
    targetLevel: "Basic",
    title: "ISC Forms: When to Use in Workflows",
    description:
      "Identify three workflow scenarios where Forms collect data better than static attributes. Forms are often overlooked in Basic enablement but critical for joiner flows.",
    steps: [
      "List three joiner/mover scenarios requiring human input (start date, manager approval notes, equipment type).",
      "For one scenario, sketch form fields and which workflow steps consume them.",
      "Deliver a two-minute voice note explaining to a new SE when to recommend a Form step.",
    ],
    successCriteria: [
      "Scenarios are realistic for enterprise HR/IT processes.",
      "Form field sketch maps to workflow variables correctly.",
      "Voice note distinguishes Forms from ServiceNow intake forms coexisting with ISC.",
    ],
    estimatedMinutes: 40,
    linkedResources: ["https://developer.sailpoint.com/discuss/t/identity-security-cloud-extensibility-the-art-of-the-possible/38184"],
    linkedSolutions: ["Identity Security Cloud", "Workflows", "Forms"],
    difficulty: "foundational",
    competencyNames: ["ISC Workflows and Forms"],
  },
  {
    id: "d4000002-0004-4000-8000-000000000001",
    targetLevel: "Senior",
    title: "Account Create Profile Transform Lab",
    description:
      "Configure transforms on an account create profile and prove they fire on net-new account provisioning — a Senior SE skill for connector-heavy deals.",
    steps: [
      "Select a lab source with create account profile support and add a transform-calculated attribute.",
      "Trigger provisioning that creates a new account (access request or role assignment).",
      "Capture provisioning transaction details showing transform output on the created account.",
    ],
    successCriteria: [
      "Evidence proves transform ran on create (not just aggregation refresh).",
      "Write-up explains testing limitations from SailPoint transform docs.",
      "Notes include rollback plan if transform caused provisioning failure.",
    ],
    estimatedMinutes: 75,
    linkedResources: ["https://developer.sailpoint.com/docs/extensibility/transforms/"],
    linkedSolutions: ["Identity Security Cloud", "Provisioning Policies", "Transforms"],
    difficulty: "intermediate",
    competencyNames: ["ISC Workflows and Forms", "Entra ID / AD Connectors"],
  },
  {
    id: "d4000002-0004-4000-8000-000000000002",
    targetLevel: "Senior",
    title: "SP Config Snapshot Export Story",
    description:
      "Use the SailPoint CLI spconfig command to export configuration artifacts for drift review — a Senior deliverable during health checks and migration assessments.",
    steps: [
      "Run `sail spconfig` export (or documented equivalent) for workflows and transforms in a lab tenant.",
      "Identify one configuration drift risk between exported JSON and Admin UI labels.",
      "Write a customer-facing paragraph on why config-as-code matters for ISC governance.",
    ],
    successCriteria: [
      "Export artifacts are listed with file names and object types.",
      "Drift example is specific and actionable.",
      "Customer paragraph ties to change control and audit requirements.",
    ],
    estimatedMinutes: 65,
    linkedResources: ["https://developer.sailpoint.com/docs/tools/cli/spconfig"],
    linkedSolutions: ["Identity Security Cloud", "SailPoint CLI", "SP Config"],
    difficulty: "intermediate",
  },
  {
    id: "d4000002-0004-4000-8000-000000000003",
    targetLevel: "Senior",
    title: "Leaver Workflow: Timed Disable Design",
    description:
      "Design a leaver workflow that disables accounts after a configurable delay, with manager notification and audit logging — common in regulated industries.",
    steps: [
      "Draft workflow outline: Identity Deleted/Modified trigger → delay → disable accounts on N sources → notify manager.",
      "Include condition branch for immediate termination vs standard voluntary leaver.",
      "Provide test plan with two personas and expected account states at T+0 and T+delay.",
    ],
    successCriteria: [
      "Workflow addresses multiple target sources explicitly.",
      "Delay mechanism uses documented ISC workflow patterns.",
      "Test plan includes rollback if disable fires prematurely.",
    ],
    estimatedMinutes: 85,
    linkedResources: ["https://developer.sailpoint.com/docs/tools/cli/workflow"],
    linkedSolutions: ["Identity Security Cloud", "Workflows", "Lifecycle"],
    difficulty: "advanced",
    competencyNames: ["ISC Workflows and Forms"],
  },
  {
    id: "d4000002-0004-4000-8000-000000000004",
    targetLevel: "Senior",
    title: "Search for Orphaned Accounts",
    description:
      "Build an ISC Search query (or CLI search) that surfaces accounts without a correlated identity — a Senior troubleshooting pattern for aggregation projects.",
    steps: [
      "Construct and run a search for uncorrelated or orphaned accounts on a target source.",
      "Export top 15 results with source, native identity, and created/modified dates.",
      "Recommend remediation play (correlation rule change vs manual correlate vs disable) for each category found.",
    ],
    successCriteria: [
      "Query syntax is valid and filters are explained in plain language.",
      "Remediation recommendations match risk level of account type.",
      "Deliverable suitable to attach to a customer weekly status deck.",
    ],
    estimatedMinutes: 55,
    linkedResources: ["https://developer.sailpoint.com/docs/tools/cli/search"],
    linkedSolutions: ["Identity Security Cloud", "ISC Search"],
    difficulty: "intermediate",
    competencyNames: ["Entra ID / AD Connectors"],
  },
  {
    id: "d4000002-0004-4000-8000-000000000005",
    targetLevel: "Senior",
    title: "Workflow Email with Dynamic Variables",
    description:
      "Configure a workflow notification email that interpolates identity, manager, and entitlement context using documented variable syntax.",
    steps: [
      "Pick a certification reminder or access request approval workflow template.",
      "Add or modify an email action with at least four dynamic fields (name, request item, due date, deep link).",
      "Send test execution and capture rendered email or workflow execution log output.",
    ],
    successCriteria: [
      "Variables resolve correctly in test output (no raw template placeholders).",
      "Email copy is professional and customer-safe.",
      "Documentation lists variables used and their source step outputs.",
    ],
    estimatedMinutes: 50,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/workflows/index.html"],
    linkedSolutions: ["Identity Security Cloud", "Workflows"],
    difficulty: "intermediate",
    competencyNames: ["ISC Workflows and Forms"],
  },
  {
    id: "d4000002-0004-4000-8000-000000000006",
    targetLevel: "Senior",
    title: "Non-Employee Lifecycle Design",
    description:
      "Architect ISC handling for contractors and non-employee identities — a Senior scenario in healthcare and SLED accounts with heavy contingent workforce.",
    steps: [
      "Document joiner, extension, and leaver flows for contractors including sponsor/manager attestation.",
      "Map each stage to ISC features (source of truth, workflows, certifications, access profiles).",
      "Identify one gap requiring HTTP orchestration or HR feed and justify the integration pattern.",
    ],
    successCriteria: [
      "Lifecycle covers expiration and automatic disable paths.",
      "Sponsor attestation is explicit in workflow design.",
      "Integration gap analysis references REST API or file-based patterns accurately.",
    ],
    estimatedMinutes: 80,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/provisioning/provisioning.html"],
    linkedSolutions: ["Identity Security Cloud", "Workflows", "Lifecycle"],
    difficulty: "advanced",
    competencyNames: ["SLED Vertical Knowledge", "ISC Workflows and Forms"],
  },
  {
    id: "d4000003-0004-4000-8000-000000000001",
    targetLevel: "Advisory",
    title: "Multi-Tenant Workflow Governance Runbook",
    description:
      "Write an Advisory runbook for promoting workflows across dev, test, and production tenants with segregation of duties and approval gates.",
    steps: [
      "Define roles (author, reviewer, deployer) and which environments each may touch.",
      "Document CLI commands for export, PR review, and import with rollback steps.",
      "Include checklist for validating triggers that differ per tenant (email domains, source IDs).",
    ],
    successCriteria: [
      "Runbook prevents single-person deploy to production without review.",
      "Rollback section includes workflow delete + redeploy prior version.",
      "Tenant-specific validation items are concrete, not generic.",
    ],
    estimatedMinutes: 90,
    linkedResources: ["https://developer.sailpoint.com/docs/tools/cli/workflow"],
    linkedSolutions: ["Identity Security Cloud", "Workflows", "SailPoint CLI"],
    difficulty: "advanced",
    competencyNames: ["Executive Demo Storytelling"],
  },
  {
    id: "d4000003-0004-4000-8000-000000000002",
    targetLevel: "Advisory",
    title: "Rules vs Transforms Workshop Facilitation",
    description:
      "Prepare and facilitate a 30-minute customer workshop on when to use transforms vs rules vs workflows, using SailPoint documentation as the source of truth.",
    steps: [
      "Build a facilitator slide outline with three customer scenarios and poll questions.",
      "Include decision tree: JSON transform → rule escalation criteria → SailPoint services involvement.",
      "Record yourself delivering the workshop opening (5 minutes) or provide detailed speaker notes.",
    ],
    successCriteria: [
      "Content cites transforms vs rules guidance from official SailPoint docs.",
      "Workshop includes time for customer architects to map their own use case.",
      "Speaker notes anticipate top three objections (maintainability, services cost, time-to-value).",
    ],
    estimatedMinutes: 85,
    linkedResources: ["https://developer.sailpoint.com/docs/extensibility/transforms/"],
    linkedSolutions: ["Identity Security Cloud", "Transforms", "Rules"],
    difficulty: "intermediate",
    competencyNames: ["Executive Demo Storytelling", "ISC Workflows and Forms"],
  },
  {
    id: "d4000003-0004-4000-8000-000000000003",
    targetLevel: "Advisory",
    title: "SoD Policy Narrative for CIO Readout",
    description:
      "Translate ISC separation-of-duties and certification capabilities into a CIO-ready risk narrative — core Advisory ASC work in enterprise deals.",
    steps: [
      "Select two SoD or toxic combination examples relevant to identity security (not generic ERP examples unless justified).",
      "Map detection, remediation, and audit evidence to ISC features.",
      "Draft a one-page CIO brief with metrics placeholders (coverage %, mean time to remediate).",
    ],
    successCriteria: [
      "Narrative leads with business risk, not product modules.",
      "Metrics section defines how ISC data would populate each KPI.",
      "Brief includes 'what we need from customer' prerequisites (role mining quality, etc.).",
    ],
    estimatedMinutes: 75,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/certifications/certifications.html"],
    linkedSolutions: ["Identity Security Cloud", "Certifications", "Governance"],
    difficulty: "advanced",
    competencyNames: ["Executive Demo Storytelling"],
  },
  {
    id: "d4000003-0004-4000-8000-000000000004",
    targetLevel: "Advisory",
    title: "SaaS Connector CLI Onboarding Story",
    description:
      "Explain the SaaS Connectivity platform and CLI connectors workflow to a customer integration lead considering custom app onboarding.",
    steps: [
      "Review `sail connectors` CLI documentation and list create/manage commands relevant to a net-new SaaS app.",
      "Outline phases: discovery → connector build → test aggregation → production promotion.",
      "Deliver a 10-slide story for a customer workshop with risks and SailPoint vs SI partner responsibilities.",
    ],
    successCriteria: [
      "Phases include testing and rollback gates.",
      "Slide story distinguishes ISC standard connectors vs custom SaaS connectivity.",
      "RACI clarifies customer admin vs SailPoint services vs partner SI.",
    ],
    estimatedMinutes: 70,
    linkedResources: ["https://developer.sailpoint.com/docs/tools/cli/connectors"],
    linkedSolutions: ["Identity Security Cloud", "SaaS Connectivity", "SailPoint CLI"],
    difficulty: "intermediate",
  },
  {
    id: "d4000003-0004-4000-8000-000000000005",
    targetLevel: "Advisory",
    title: "Agent Identity (AIS) Executive Briefing",
    description:
      "Build an executive briefing on SailPoint Agent Identity Security for a CISO audience — connecting machine/agent identities to governance gaps customers already feel.",
    steps: [
      "Research AIS positioning from SailPoint materials and identify three customer pain points (shadow AI, NHI sprawl, audit).",
      "Map each pain to AIS capabilities without feature-dumping.",
      "Record or script a seven-minute executive briefing with a crisp call-to-action for a workshop.",
    ],
    successCriteria: [
      "Briefing distinguishes human vs non-human identity governance.",
      "Pain points are specific to a chosen vertical (e.g., healthcare or SLED).",
      "CTA proposes measurable next step (assessment, pilot scope, stakeholder map).",
    ],
    estimatedMinutes: 80,
    linkedResources: ["https://www.sailpoint.com/products/agent-identity-security"],
    linkedSolutions: ["Agent Identity Security", "Identity Security Cloud"],
    difficulty: "advanced",
    competencyNames: ["Executive Demo Storytelling", "SLED Vertical Knowledge"],
  },
  {
    id: "d4000003-0004-4000-8000-000000000006",
    targetLevel: "Advisory",
    title: "Identity Split/Merge Governance Playbook",
    description:
      "Document governance controls when identities must be split or merged after M&A or HR data corrections — an Advisory playbook that prevents audit findings.",
    steps: [
      "Define triggers for split vs merge and approval roles required before execution.",
      "Map technical steps in ISC (manual correlation, identity refresh, access recertification).",
      "Include communication templates for application owners affected by access changes.",
    ],
    successCriteria: [
      "Playbook requires documented approval before merge/split execution.",
      "Technical steps reference ISC admin capabilities accurately.",
      "Templates include timeline expectations and rollback contacts.",
    ],
    estimatedMinutes: 75,
    linkedResources: ["https://documentation.sailpoint.com/saas/help/provisioning/identity_profiles.html"],
    linkedSolutions: ["Identity Security Cloud", "Governance"],
    difficulty: "intermediate",
    competencyNames: ["Executive Demo Storytelling"],
  },
];
