import type { ChallengeLibraryEntry } from "@/lib/challenges/challenge-library-types";

type ChallengeSeed = {
  n: number;
  level: ChallengeLibraryEntry["targetLevel"];
  difficulty: ChallengeLibraryEntry["difficulty"];
  title: string;
  description: string;
  steps: [string, string, string];
  success: [string, string, string];
  minutes: number;
  solutions: string[];
  competencies: string[];
  resources?: string[];
};

const BATCH_PREFIX = "f5000001-0005-4000-8000";

function entry(seed: ChallengeSeed): ChallengeLibraryEntry {
  const id = `${BATCH_PREFIX}-${String(seed.n).padStart(12, "0")}`;
  return {
    id,
    targetLevel: seed.level,
    title: seed.title,
    description: seed.description,
    steps: [...seed.steps],
    successCriteria: [...seed.success],
    estimatedMinutes: seed.minutes,
    linkedResources: seed.resources ?? ["https://documentation.sailpoint.com/saas/help/"],
    linkedSolutions: seed.solutions,
    difficulty: seed.difficulty,
    competencyNames: seed.competencies,
  };
}

const WORKFLOW_SEEDS: ChallengeSeed[] = [
  { n: 1, level: "Basic", difficulty: "foundational", title: "Joiner Workflow: Trigger to Provision", minutes: 50, solutions: ["ISC Workflows"], competencies: ["ISC Workflows and Forms"], description: "Build and document a joiner workflow from identity-created trigger through provisioning — the most common customer lifecycle ask.", steps: ["Map trigger event and first three workflow steps in your lab.", "Document approval vs auto-provision decision points.", "Record a customer-facing explanation of audit trail."], success: ["Trigger classification is correct.", "Steps use ISC workflow terminology.", "Audit narrative is business-readable."] },
  { n: 2, level: "Basic", difficulty: "foundational", title: "Leaver Workflow: Disable vs Delete", minutes: 45, solutions: ["ISC Workflows"], competencies: ["ISC Workflows and Forms"], description: "Compare disable-on-leaver vs delayed delete patterns and when each fits customer policy.", steps: ["Configure or diagram a leaver workflow with manager attestation.", "List downstream systems affected in your lab.", "Write recommendation for a 500-person agency."], success: ["Attestation step is present.", "Downstream impacts named.", "Recommendation cites compliance driver."] },
  { n: 3, level: "Basic", difficulty: "intermediate", title: "Mover Workflow: Role Change Propagation", minutes: 55, solutions: ["ISC Workflows"], competencies: ["ISC Workflows and Forms"], description: "Handle department transfer with access add/remove orchestration.", steps: ["Document mover trigger and variable passing between steps.", "Show before/after entitlements on a test identity.", "Explain timing risks if provisioning lags."], success: ["Variables documented.", "Entitlement delta visible.", "Risk called out with mitigation."] },
  { n: 4, level: "Senior", difficulty: "intermediate", title: "HTTP Workflow Action: Ticketing Integration", minutes: 60, solutions: ["ISC Workflows", "HTTP"], competencies: ["ISC Workflows and Forms"], description: "Use HTTP action to open a ServiceNow or Jira ticket from a workflow — common enterprise pattern.", steps: ["Build HTTP step with auth header pattern (redact secrets).", "Map response handling and failure branch.", "Demo idempotency if workflow replays."], success: ["HTTP payload documented.", "Failure branch exists.", "Idempotency addressed."] },
  { n: 5, level: "Senior", difficulty: "advanced", title: "Nested Transform Chain Lab", minutes: 70, solutions: ["Transforms"], competencies: ["ISC Workflows and Forms"], description: "Chain Replace, Concat, and Lower transforms for account create profiles — Senior SE skill.", steps: ["Implement three-step transform on one attribute.", "Export rule fragments.", "Explain debugging when aggregation shows wrong value."], success: ["Transform chain correct.", "Export included.", "Debug narrative plausible."] },
  { n: 6, level: "Basic", difficulty: "foundational", title: "Workflow Form: Manager Data Collection", minutes: 40, solutions: ["ISC Forms"], competencies: ["ISC Workflows and Forms"], description: "Create a form step that collects manager-supplied joiner attributes before provisioning.", steps: ["Add form fields with validation.", "Wire form output into provision step.", "Screenshot completed form submission."], success: ["Validation present.", "Provision uses form fields.", "Evidence complete."] },
  { n: 7, level: "Senior", difficulty: "intermediate", title: "Certification Campaign Trigger Workflow", minutes: 55, solutions: ["Certifications", "Workflows"], competencies: ["ISC Workflows and Forms", "Governance"], description: "Automate campaign launch when risk threshold detected in Search.", steps: ["Document trigger from Search or scheduled event.", "Link to certification definition.", "Write ops runbook for false positives."], success: ["Trigger documented.", "Campaign linked.", "Runbook practical."] },
  { n: 8, level: "Advisory", difficulty: "advanced", title: "Multi-Tenant Workflow Promotion", minutes: 90, solutions: ["SailPoint CLI", "Workflows"], competencies: ["ISC Workflows and Forms"], description: "Promote workflow JSON from dev to prod with change control — Advisory ASC pattern.", steps: ["Export workflow from dev via CLI.", "Document promotion checklist.", "List rollback steps."], success: ["CLI evidence.", "Checklist complete.", "Rollback defined."] },
  { n: 9, level: "Basic", difficulty: "intermediate", title: "Email Notification Step Best Practices", minutes: 35, solutions: ["ISC Workflows"], competencies: ["ISC Workflows and Forms"], description: "Design notification steps that executives actually read during approvals.", steps: ["Create two notification templates: manager vs auditor.", "Include deep links and SLA language.", "A/B explain which you would use in SLED."], success: ["Templates differ by audience.", "Deep links work.", "SLED context applied."] },
  { n: 10, level: "Senior", difficulty: "intermediate", title: "Provisioning Retry and Error Branch", minutes: 50, solutions: ["Provisioning"], competencies: ["ISC Workflows and Forms"], description: "Model transient connector failure with retry and escalation.", steps: ["Add retry loop with max attempts.", "Escalation to human task or ticket.", "Log fields for support."], success: ["Retry bounded.", "Escalation path clear.", "Logging adequate."] },
  { n: 11, level: "Basic", difficulty: "foundational", title: "Birthright Access via Workflow", minutes: 45, solutions: ["Access Profiles"], competencies: ["ISC Workflows and Forms"], description: "Explain birthright provisioning vs access request for default entitlements.", steps: ["Map one birthright bundle in lab.", "Contrast with self-service path.", "Talk track for IAM manager."], success: ["Bundle mapped.", "Contrast accurate.", "Talk track clear."] },
  { n: 12, level: "Senior", difficulty: "advanced", title: "SoD Check Before Provision", minutes: 65, solutions: ["SoD", "Workflows"], competencies: ["Governance", "ISC Workflows and Forms"], description: "Insert segregation-of-duties validation before high-risk provision.", steps: ["Identify toxic combination in policy library.", "Wire workflow branch on violation.", "Document exception handling."], success: ["SoD rule cited.", "Branch on violation.", "Exception process defined."] },
  { n: 13, level: "Advisory", difficulty: "advanced", title: "Workflow Performance at Scale", minutes: 75, solutions: ["ISC Workflows"], competencies: ["ISC Workflows and Forms"], description: "Advise customer with 50k identities on workflow concurrency and batching.", steps: ["Profile a heavy workflow in lab.", "List three scale optimizations.", "Executive summary for steering committee."], success: ["Profiling attempted.", "Optimizations specific.", "Exec summary outcome-focused."] },
  { n: 14, level: "Basic", difficulty: "foundational", title: "Scheduled Workflow: Quarterly Attestation", minutes: 40, solutions: ["Workflows"], competencies: ["ISC Workflows and Forms"], description: "Configure time-based workflow for recurring manager attestation.", steps: ["Set schedule and timezone considerations.", "Document owner and failure alerts.", "Customer email announcing process."], success: ["Schedule correct.", "Alerts defined.", "Customer comms professional."] },
  { n: 15, level: "Senior", difficulty: "intermediate", title: "Contractor Lifecycle Workflow", minutes: 55, solutions: ["NERM", "Workflows"], competencies: ["ISC Workflows and Forms"], description: "Joiner-extension-leaver for contractors with sponsor attestation.", steps: ["Map three phases with triggers.", "Highlight expiration handling.", "Compare to employee joiner differences."], success: ["Three phases mapped.", "Expiration handled.", "Comparison accurate."] },
  { n: 16, level: "Basic", difficulty: "intermediate", title: "Workflow Variable: Define and Pass", minutes: 45, solutions: ["Workflows"], competencies: ["ISC Workflows and Forms"], description: "Master define-variable and reference syntax across steps.", steps: ["Create three variables in one workflow.", "Pass across HTTP and provision steps.", "Screenshot variable inspector."], success: ["Three variables used.", "Cross-step references work.", "Screenshots included."] },
  { n: 17, level: "Advisory", difficulty: "advanced", title: "Workflow Design Review Facilitation", minutes: 80, solutions: ["Workflows"], competencies: ["ISC Workflows and Forms", "Executive Demo Storytelling"], description: "Facilitate customer workshop to prioritize 5 workflows for phase 1.", steps: ["Prepare facilitation agenda.", "Capture customer priorities matrix.", "Deliver mutual action plan."], success: ["Agenda professional.", "Matrix completed.", "MAP with owners."] },
  { n: 18, level: "Senior", difficulty: "intermediate", title: "Access Request Approval Workflow Tuning", minutes: 50, solutions: ["Access Requests"], competencies: ["ISC Workflows and Forms"], description: "Reduce approval fatigue while maintaining SoD — tune escalation paths.", steps: ["Document current approval chain.", "Propose one simplification with risk note.", "Measure before/after step count."], success: ["Chain documented.", "Simplification justified.", "Metrics included."] },
  { n: 19, level: "Basic", difficulty: "foundational", title: "Workflow Testing Checklist", minutes: 35, solutions: ["Workflows"], competencies: ["ISC Workflows and Forms"], description: "Create repeatable test cases before promoting any customer workflow.", steps: ["Write 5 test cases: happy path and failures.", "Execute in lab with evidence.", "Share checklist template with team."], success: ["Five cases written.", "Evidence of runs.", "Template reusable."] },
  { n: 20, level: "Senior", difficulty: "advanced", title: "Event Trigger: Identity Attribute Change", minutes: 60, solutions: ["Workflows"], competencies: ["ISC Workflows and Forms"], description: "Trigger workflow on attribute change with debounce considerations.", steps: ["Configure attribute-change trigger.", "Explain storm scenario if HR feed flaps.", "Mitigation documented."], success: ["Trigger works.", "Storm scenario explained.", "Mitigation practical."] },
  { n: 21, level: "Advisory", difficulty: "advanced", title: "Workflow Observability Dashboard", minutes: 70, solutions: ["ISC", "Search"], competencies: ["ISC Workflows and Forms", "Governance"], description: "Build Search queries leadership uses to monitor workflow failures weekly.", steps: ["Create three Search queries for failures and SLA breaches.", "Draft weekly email template for IAM lead.", "Link to remediation playbooks."], success: ["Queries return useful fields.", "Email template executive-ready.", "Playbooks linked."] },
  { n: 22, level: "Basic", difficulty: "intermediate", title: "Parallel Approval Paths", minutes: 50, solutions: ["Workflows"], competencies: ["ISC Workflows and Forms"], description: "Model parallel manager + data-owner approval before provision.", steps: ["Diagram parallel branches and join.", "Implement or simulate in lab.", "Explain timeout if one approver ghosts."], success: ["Diagram clear.", "Lab evidence.", "Timeout handling defined."] },
  { n: 23, level: "Senior", difficulty: "intermediate", title: "Workflow + Access Request Integration", minutes: 55, solutions: ["Access Requests", "Workflows"], competencies: ["ISC Workflows and Forms"], description: "Connect self-service catalog item to custom workflow extension.", steps: ["Trace request from catalog to workflow.", "Document extension point.", "Demo one custom approval rule."], success: ["Trace complete.", "Extension identified.", "Demo recorded or scripted."] },
  { n: 24, level: "Basic", difficulty: "foundational", title: "Workflow Naming and Documentation Standards", minutes: 30, solutions: ["Workflows"], competencies: ["ISC Workflows and Forms"], description: "Establish customer naming convention for workflows — prevents demo chaos.", steps: ["Propose naming standard with examples.", "Retrofit three lab workflows.", "One-page customer-facing catalog."], success: ["Standard sensible.", "Retrofit done.", "Catalog readable."] },
  { n: 25, level: "Advisory", difficulty: "advanced", title: "Workflow Center of Excellence Charter", minutes: 85, solutions: ["ISC Workflows"], competencies: ["ISC Workflows and Forms", "Executive Demo Storytelling"], description: "Draft CoE charter for customer workflow governance post go-live.", steps: ["Define roles: builder, reviewer, operator.", "Include change advisory board hooks.", "Present 10-slide outline."], success: ["Roles defined.", "CAB hooks realistic.", "Slides outcome-oriented."] },
];

export const SAILPOINT_CHALLENGE_LIBRARY_BATCH4: ChallengeLibraryEntry[] = WORKFLOW_SEEDS.map(entry);
