import type { ChallengeLibraryEntry } from "@/lib/challenges/challenge-library-types";

type ChallengeSeed = {
  n: number;
  level: ChallengeLibraryEntry["targetLevel"];
  difficulty: ChallengeLibraryEntry["difficulty"];
  title: string;
  description: string;
  steps: [string, string, string];
  success: [string, string, string];
  minutes: number;
  solutions: string[];
  competencies: string[];
};

const BATCH_PREFIX = "c6000001-0006-4000-8000";

function entry(seed: ChallengeSeed): ChallengeLibraryEntry {
  return {
    id: `${BATCH_PREFIX}-${String(seed.n).padStart(12, "0")}`,
    targetLevel: seed.level,
    title: seed.title,
    description: seed.description,
    steps: [...seed.steps],
    successCriteria: [...seed.success],
    estimatedMinutes: seed.minutes,
    linkedResources: ["https://documentation.sailpoint.com/"],
    linkedSolutions: seed.solutions,
    difficulty: seed.difficulty,
    competencyNames: seed.competencies,
  };
}

const MIXED_SEEDS: ChallengeSeed[] = [
  { n: 1, level: "Basic", difficulty: "foundational", title: "ISC Search: Stale Admin Accounts", minutes: 40, solutions: ["ISC Search"], competencies: ["ISC Search"], description: "Build Search query finding admin accounts inactive 90+ days — classic discovery win.", steps: ["Write and save query.", "Export sample results.", "Explain remediation workflow."], success: ["Query correct.", "Export included.", "Remediation practical."] },
  { n: 2, level: "Senior", difficulty: "intermediate", title: "Entra ID Connector: Delta Aggregation", minutes: 55, solutions: ["Entra Connector"], competencies: ["Entra ID / AD Connectors"], description: "Explain delta vs full aggregation for Microsoft Entra source.", steps: ["Document schedule in lab.", "Show delta log evidence.", "Customer FAQ on failures."], success: ["Schedule documented.", "Log evidence.", "FAQ addresses outages."] },
  { n: 3, level: "Advisory", difficulty: "advanced", title: "ISC vs IIQ: Migration Decision Tree", minutes: 75, solutions: ["IIQ", "ISC"], competencies: ["Competitive Positioning"], description: "Advisory guide: when to recommend IIQ vs ISC vs coexistence.", steps: ["Decision tree with 6 branches.", "Three customer archetypes.", "Talk track for existing IIQ customer."], success: ["Tree complete.", "Archetypes distinct.", "Talk track honest."] },
  { n: 4, level: "Basic", difficulty: "intermediate", title: "Access Profile vs Entitlement Explainer", minutes: 35, solutions: ["Access Profiles"], competencies: ["Governance"], description: "Video explainer for new SEs on access profile layering.", steps: ["Script 4-minute video.", "Record or storyboard.", "Quiz teammate."], success: ["Script accurate.", "Recording/storyboard done.", "Peer validated."] },
  { n: 5, level: "Senior", difficulty: "intermediate", title: "Certification: Manager vs Entitlement Owner", minutes: 50, solutions: ["Certifications"], competencies: ["Governance"], description: "Design campaign with mixed certifier types.", steps: ["Configure campaign in lab.", "Document certifier selection logic.", "Escalation for non-response."], success: ["Campaign configured.", "Logic documented.", "Escalation defined."] },
  { n: 6, level: "Basic", difficulty: "foundational", title: "Password Reset Self-Service Demo", minutes: 30, solutions: ["Password Management"], competencies: ["Entra ID / AD Connectors"], description: "Demo password reset integration for helpdesk reduction story.", steps: ["Configure or script demo.", "Measure steps vs call to helpdesk.", "SLED ROI talking point."], success: ["Demo works.", "Steps counted.", "ROI stated."] },
  { n: 7, level: "Senior", difficulty: "advanced", title: "Custom Connector Scoping Workshop", minutes: 70, solutions: ["Connectors"], competencies: ["Entra ID / AD Connectors"], description: "Facilitate scoping for homegrown app connector.", steps: ["Account schema worksheet.", "Aggregation and provision requirements.", "Effort estimate ranges."], success: ["Schema complete.", "Requirements clear.", "Estimate bounded."] },
  { n: 8, level: "Advisory", difficulty: "advanced", title: "Identity Program Maturity Assessment", minutes: 90, solutions: ["ISC"], competencies: ["Executive Demo Storytelling", "Governance"], description: "Run maturity assessment and produce 12-month roadmap.", steps: ["Score 8 domains.", "Gap narrative.", "Phased roadmap with quick wins."], success: ["Scores justified.", "Gaps prioritized.", "Roadmap actionable."] },
  { n: 9, level: "Basic", difficulty: "intermediate", title: "Role Mining: Suggest vs Manual", minutes: 45, solutions: ["Roles"], competencies: ["Governance"], description: "Compare role mining suggestions to manual role design.", steps: ["Run mining in lab.", "Accept/reject three suggestions with rationale.", "Customer guidance on when to trust mining."], success: ["Mining executed.", "Rationale documented.", "Guidance practical."] },
  { n: 10, level: "Senior", difficulty: "intermediate", title: "NERM: Sponsor Attestation Flow", minutes: 50, solutions: ["NERM"], competencies: ["Governance"], description: "Non-employee sponsor attestation for contractor access.", steps: ["Map sponsor workflow.", "Expiration notifications.", "Audit report fields."], success: ["Workflow mapped.", "Notifications timed.", "Audit fields listed."] },
  { n: 11, level: "Basic", difficulty: "foundational", title: "Identity Profile: Authoritative Source", minutes: 40, solutions: ["Identity Profiles"], competencies: ["Entra ID / AD Connectors"], description: "Set authoritative HR source and explain downstream impact.", steps: ["Configure authoritative source.", "Show attribute precedence.", "Conflict scenario write-up."], success: ["Source set.", "Precedence shown.", "Conflict explained."] },
  { n: 12, level: "Senior", difficulty: "advanced", title: "Privileged Access: PAM Integration Story", minutes: 65, solutions: ["PAM Integration"], competencies: ["Governance"], description: "Integrate ISC with CyberArk or similar for privileged session governance.", steps: ["Architecture diagram.", "Certification touchpoints.", "Demo script segment."], success: ["Diagram accurate.", "Cert integration clear.", "Demo segment timed."] },
  { n: 13, level: "Advisory", difficulty: "advanced", title: "Okta Competitive: Identity Governance", minutes: 80, solutions: ["ISC"], competencies: ["Competitive Positioning"], description: "Governance-led bake-off vs Okta without feature dumping.", steps: ["Three discovery traps for Okta.", "ISC differentiation pillars.", "Mock bake-off debrief."], success: ["Traps ethical.", "Pillars outcome-based.", "Debrief recorded."] },
  { n: 14, level: "Basic", difficulty: "intermediate", title: "SailPoint CLI: First Workflow Deploy", minutes: 50, solutions: ["SailPoint CLI"], competencies: ["ISC Workflows and Forms"], description: "Deploy workflow from CLI using PAT auth — field readiness skill.", steps: ["Authenticate with sail CLI.", "Deploy sample workflow.", "Document env var pattern."], success: ["Auth works.", "Deploy succeeds.", "Env pattern documented."] },
  { n: 15, level: "Senior", difficulty: "intermediate", title: "Data Segregation: Multi-Org ISC", minutes: 55, solutions: ["ISC"], competencies: ["Governance"], description: "Explain org segmentation for MSP or holding company.", steps: ["Diagram two-org model.", "Search and cert boundaries.", "Cross-org risks."], success: ["Diagram clear.", "Boundaries defined.", "Risks named."] },
  { n: 16, level: "Basic", difficulty: "foundational", title: "Governance Dashboard Tour", minutes: 35, solutions: ["ISC"], competencies: ["Governance"], description: "Navigate governance dashboards for executive readout.", steps: ["Screenshot three key widgets.", "Write executive one-pager.", "Practice 3-minute tour."], success: ["Widgets relevant.", "One-pager crisp.", "Tour practiced."] },
  { n: 17, level: "Senior", difficulty: "advanced", title: "SOD Policy Library: Toxic Combination", minutes: 60, solutions: ["SoD"], competencies: ["Governance"], description: "Implement and test one toxic combination policy end-to-end.", steps: ["Define policy.", "Trigger violation in lab.", "Remediation workflow."], success: ["Policy active.", "Violation reproduced.", "Remediation defined."] },
  { n: 18, level: "Advisory", difficulty: "advanced", title: "FedRAMP Customer: ISC Boundary", minutes: 85, solutions: ["ISC"], competencies: ["Governance"], description: "Explain ISC FedRAMP boundary and customer responsibilities.", steps: ["Shared responsibility matrix.", "Common ATO questions.", "Brief for federal SE shadow."], success: ["Matrix accurate.", "FAQ complete.", "Brief delivered."] },
  { n: 19, level: "Basic", difficulty: "intermediate", title: "Mobile App: Access Request Approval", minutes: 40, solutions: ["Mobile"], competencies: ["Access Requests"], description: "Demo mobile approval for access requests — executive convenience story.", steps: ["Complete mobile approval in lab.", "Screenshot audit trail.", "Security talking points."], success: ["Approval completed.", "Audit trail shown.", "Security addressed."] },
  { n: 20, level: "Senior", difficulty: "intermediate", title: "Integration: ServiceNow IGA Ticket", minutes: 55, solutions: ["ServiceNow"], competencies: ["ISC Workflows and Forms"], description: "Bi-directional ServiceNow ticket for access fulfillment.", steps: ["Ticket create on request.", "Status sync back.", "Failure handling."], success: ["Ticket created.", "Sync documented.", "Failures handled."] },
  { n: 21, level: "Basic", difficulty: "foundational", title: "SailPoint IdentityNow Branding", minutes: 25, solutions: ["ISC"], competencies: ["Executive Demo Storytelling"], description: "Correctly use ISC vs IdentityNow naming in customer materials.", steps: ["Audit one deck for naming.", "Fix inconsistencies.", "Share style guide snippet."], success: ["Audit done.", "Fixes applied.", "Guide shared."] },
  { n: 22, level: "Senior", difficulty: "advanced", title: "Disaster Recovery: ISC Tenant", minutes: 70, solutions: ["ISC"], competencies: ["Governance"], description: "Customer DR runbook for ISC — RPO/RTO and failover steps.", steps: ["DR architecture overview.", "Runbook steps.", "Tabletop exercise notes."], success: ["Architecture cited.", "Runbook ordered.", "Tabletop documented."] },
  { n: 23, level: "Advisory", difficulty: "advanced", title: "Partner Co-Sell: SI Delivery Model", minutes: 75, solutions: ["ISC"], competencies: ["Executive Demo Storytelling"], description: "Position SailPoint + SI partner for complex workflow delivery.", steps: ["RACI SailPoint vs SI.", "Statement of work outline.", "Risk mitigation for SI quality."], success: ["RACI clear.", "SOW outline realistic.", "Risks mitigated."] },
  { n: 24, level: "Basic", difficulty: "intermediate", title: "Peer Teaching: One ISC Concept", minutes: 45, solutions: ["ISC"], competencies: ["Executive Demo Storytelling"], description: "Teach one ISC concept to another SE in 15-minute session.", steps: ["Pick concept and learning objectives.", "Deliver session.", "Collect feedback and iterate."], success: ["Objectives met.", "Session delivered.", "Feedback incorporated."] },
  { n: 25, level: "Senior", difficulty: "intermediate", title: "Market Pulse: Identity Trends Brief", minutes: 50, solutions: ["ISC", "AIS"], competencies: ["Competitive Positioning"], description: "Monthly trends brief tying NHI and agentic news to SailPoint.", steps: ["Three news items analyzed.", "SailPoint angle each.", "Share in team channel."], success: ["Items current.", "Angles specific.", "Shared with team."] },
  { n: 26, level: "Advisory", difficulty: "advanced", title: "Executive QBR: Identity Metrics", minutes: 85, solutions: ["ISC"], competencies: ["Executive Demo Storytelling", "Governance"], description: "Build quarterly business review deck for customer IAM steering committee.", steps: ["Five KPIs with trends.", "Risk register update.", "Next quarter priorities."], success: ["KPIs meaningful.", "Risks current.", "Priorities agreed format."] },
  { n: 27, level: "Basic", difficulty: "foundational", title: "Lab Tenant Hygiene Checklist", minutes: 30, solutions: ["ISC"], competencies: ["ISC Search"], description: "Weekly lab hygiene so demos never break.", steps: ["Checklist of 10 items.", "Execute once.", "Schedule recurring reminder."], success: ["Checklist complete.", "Execution logged.", "Reminder set."] },
  { n: 28, level: "Senior", difficulty: "intermediate", title: "API Rate Limits and Pagination", minutes: 50, solutions: ["ISC API"], competencies: ["ISC Workflows and Forms"], description: "Handle ISC API pagination in integration script or workflow.", steps: ["Script paginated identity export.", "Document rate limit headers.", "Error retry pattern."], success: ["Export complete.", "Limits documented.", "Retry implemented."] },
  { n: 29, level: "Basic", difficulty: "intermediate", title: "Deal Prep: Technical Discovery Checklist", minutes: 40, solutions: ["ISC"], competencies: ["Executive Demo Storytelling"], description: "Build reusable technical discovery checklist for first customer call.", steps: ["25 questions across sources, apps, governance.", "Prioritize top 10.", "Use on mock discovery."], success: ["25 questions.", "Top 10 ranked.", "Mock discovery notes."] },
  { n: 30, level: "Advisory", difficulty: "advanced", title: "Multi-Year Identity Roadmap Facilitation", minutes: 90, solutions: ["ISC", "AIS"], competencies: ["Executive Demo Storytelling", "Agentic Fabric"], description: "Facilitate 3-year roadmap including human and machine identity.", steps: ["Year 1-3 capability phases.", "Investment themes.", "Executive readout deck."], success: ["Phases logical.", "Investment aligned.", "Deck executive-ready."] },
];

export const SAILPOINT_CHALLENGE_LIBRARY_BATCH6: ChallengeLibraryEntry[] = MIXED_SEEDS.map(entry);
